<template>
  <DetailDrawer class="customer-hub-drawer" v-model="visible" append-to-body title="客户事项" width="760px" :before-close="beforeClose">
    <el-alert v-if="error" :title="error" type="error" show-icon :closable="false" />
    <GlassButton variant="secondary" :loading="loading" @click="load">刷新事项（保留输入）</GlassButton>
    <div v-if="item" v-loading="loading" class="item-detail">
      <header><h2>{{ item.title }}</h2><p>{{ item.customer_name }} · {{ ITEM_STATE_LABELS[item.state] || item.state }} · 版本 {{ item.row_version }}</p></header>
      <section><h3>目标与来源</h3><p>{{ readableValue(item.goal_definition) || '目标定义未提供' }}</p><p>目标类型：{{ item.goal_type || '未提供' }} · 来源修订：{{ item.source_revision ?? '来源未提供' }}</p><p v-if="item.review_at">再核验：{{ date(item.review_at) }} · {{ item.waiting_kind || '未提供等待对象' }}</p><p v-if="item.pause_reason">暂停原因：{{ item.pause_reason }}</p><p v-if="item.resume_condition">恢复条件：{{ item.resume_condition }}</p><p v-if="item.result_validity === 'review_required'" class="warning">结果证据已失效，需要复核或显式重开；此前解决记录仍保留。</p></section>
      <section><h3>行动 · 完成一次行动需另行核验目标</h3><article v-for="action in item.actions" :key="action.action_id"><strong>{{ action.next_action || action.action_type }}</strong><p>{{ action.effective_status || action.status }} · {{ action.owner_name || '负责人未提供' }}</p><p>原期限 {{ date(action.original_due_at) }} · 业务期限 {{ date(action.business_due_at) }} · 提醒 {{ date(action.effective_due_at) }}</p><GlassButton v-any-permission="['customer_radar:write','customer:admin']" variant="link" :disabled="!action.can_operate" @click="actionEditor.open(action)">登记行动结果</GlassButton></article><el-empty v-if="!item.actions?.length" description="暂无可见行动" :image-size="48" /></section>
      <section><h3>源任务与必需依赖</h3><article v-for="(dependency,index) in item.dependencies" :key="dependency.id || index"><strong>{{ dependency.source_domain }} #{{ dependency.source_id }}</strong><p>{{ dependency.required ? '必须完成' : '辅助参考' }} · {{ dependency.status || '状态未核验' }} · 来源版本 {{ dependency.source_revision ?? '未提供' }}</p><router-link v-if="dependency.deep_link" :to="dependency.deep_link">进入源模块</router-link></article><p v-if="!item.dependencies?.length">暂无关联依赖</p></section>
      <section><h3>准备工作与持续委派</h3><p>仅授权研究、核验和草稿准备；对外发送、当前报价和交期承诺仍走各自入口。</p><article v-for="delegation in item.delegations" :key="delegation.id"><strong>{{ delegation.goal }}</strong><p>{{ DELEGATION_STATE_LABELS[delegation.state] || '状态未提供' }} · {{ RUN_STATE_LABELS[delegation.run_status] || '本轮尚未创建' }}</p><p v-if="delegation.outcome_uncertain">运行结果不确定，需要查询原运行回执；恢复不会重复发起执行。</p><p v-else-if="delegation.stop_requested">已禁止新动作，已请求停止在途执行，等待真实停止回执。</p><p v-if="delegation.readiness?.gaps?.length">{{ delegation.readiness.gaps.join('；') }}</p><p v-else-if="delegation.readiness?.worker_status === 'configured_not_observed'">执行配置已就绪，实际开始以领取和执行回执为准。</p><p v-if="delegation.review_at">再核验：{{ date(delegation.review_at) }} · {{ delegation.resume_condition }}</p><div class="operation-buttons"><GlassButton v-for="op in delegation.allowed_operations || []" :key="op" v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="link" :disabled="saving" @click="openDelegationOperation(delegation,op)">{{ {pause:'暂停委派',resume:'恢复委派',cancel:'终止委派'}[op] || op }}</GlassButton></div></article><el-input v-model="delegationGoal" type="textarea" :rows="2" placeholder="明确准备目标，例如核验客户样品需求并准备回复草稿" /><GlassButton v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="secondary" :loading="saving" :disabled="!item.can_operate || item.source_valid !== true || ['paused','blocked','resolved','cancelled'].includes(item.state) || !delegationGoal.trim()" @click="delegate">委派准备工作</GlassButton></section>
      <section><h3>准备产物 · 质量与采纳分开记录</h3><article v-for="artifact in item.prepared_artifacts" :key="`${artifact.target_id}-${artifact.target_revision}`"><strong>{{ artifact.title }}</strong><p>{{ artifact.status }} · 质量 {{ artifact.review_status || '未提供' }} · 来源版本 {{ artifact.source_revision ?? '未提供' }}</p><p>{{ readableValue(artifact.content) }}</p><p v-if="!artifact.can_adopt" class="warning">当前产物不可采纳，需确认质量与来源有效性。</p><GlassButton v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="link" @click="openFeedback(artifact)">分别评价事实、适用与采纳</GlassButton></article><p v-if="!item.prepared_artifacts?.length">暂无准备产物；不代表已经执行或发送。</p></section>
      <section><h3>结果与历史</h3><p>{{ item.resolution_summary || '尚未登记事项目标结果' }}</p><p>{{ readableValue(item.resolution_evidence) }}</p><el-timeline><el-timeline-item v-for="(event,index) in item.history" :key="event.id || index" :timestamp="date(event.occurred_at)"><strong>{{ event.event_type }}</strong><p>{{ event.reason }} · {{ event.from_state }} → {{ event.to_state }}</p><p v-if="event.delivery_plan">已决定方案：{{ event.delivery_plan }} · {{ event.delivery_decision === 'alternative' ? '替代方案' : '按原交期执行' }}</p><p v-if="event.customer_decision">客户决定：{{ event.customer_decision === 'accepted' ? '已接受' : event.customer_decision }}</p><p>{{ readableValue(event.evidence_refs) }}</p></el-timeline-item></el-timeline><router-link v-if="item.deep_link" :to="item.deep_link">打开同一客户作战卡</router-link></section>
      <section v-if="operations.length"><h3>推进这个目标</h3><el-select v-model="operation" placeholder="选择操作"><el-option v-for="op in operations" :key="op" :value="op" :label="ITEM_OPERATION_LABELS[op]" /></el-select><el-form label-position="top" v-if="operation" :disabled="saving"><el-form-item label="原因 / 结果摘要"><el-input v-model="form.reason" type="textarea" :rows="3" /></el-form-item><template v-if="operation === 'record_delivery_plan'"><p>先在已授权渠道发送决定的方案，再选取同一条真实出站消息；客户回复和源模块履约将分别验收。</p><el-form-item label="方案决定"><el-select v-model="form.delivery_decision"><el-option label="替代方案" value="alternative" /><el-option label="按原交期执行" value="original_schedule" /></el-select></el-form-item><el-form-item label="已决定的交付方案"><el-input v-model="form.delivery_plan" type="textarea" :rows="3" /></el-form-item></template><el-form-item v-if="['pause','wait'].includes(operation)" label="恢复 / 继续条件"><el-input v-model="form.resume_condition" /></el-form-item><el-form-item v-if="operation === 'wait'" label="等待对象"><el-select v-model="form.waiting_kind"><el-option label="客户" value="customer" /><el-option label="同事" value="colleague" /><el-option label="源任务" value="source" /></el-select></el-form-item><el-form-item v-if="['wait','block','snooze','record_delivery_plan'].includes(operation)" label="再核验时间（北京时间）"><el-date-picker v-model="form.review_at" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" /></el-form-item><template v-if="['resolve','revalidate','reverify','reopen','record_delivery_plan'].includes(operation)"><p v-if="operation === 'reverify'">选择当前有效的来源证据并说明核验结论。系统会复核必需依赖、终止旧的过期行动并准备新的内部核验；已暂停的事项会保留暂停状态。</p><p v-else-if="operation === 'record_delivery_plan'">请选择已发送方案的真实出站消息，客户回复需在同一会话中晚于该消息。</p><p v-else>结果确认与重开均需明确来源证据。解决必须满足目标及必需依赖，服务端会复核证据适配性。</p><el-form-item v-if="item.goal_type === 'delivery_exception' && ['resolve','revalidate'].includes(operation)" label="客户对对应方案的决定"><el-select v-model="form.customer_decision"><el-option label="已接受" value="accepted" /><el-option label="已拒绝" value="declined" /><el-option label="尚未确认" value="unclear" /></el-select><p>请选择同一会话里晚于方案消息的真实客户回复；还须等待源模块履约完成。</p></el-form-item><el-checkbox v-if="['resolve','revalidate'].includes(operation)" v-model="form.cancel_remaining">明确取消剩余非必需行动（必需依赖仍须完成）</el-checkbox><el-radio-group v-if="operation !== 'record_delivery_plan'" v-model="evidenceKind"><el-radio value="event">沟通结果</el-radio><el-radio value="fact">事实证据</el-radio><el-radio value="message">真实往来消息</el-radio></el-radio-group><EvidencePicker v-model="form.evidence_refs" :customer-id="item.customer_id" :kind="evidenceKind" references :disabled="saving" /></template></el-form><GlassButton v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="primary" :loading="saving" :disabled="!operation" @click="transition">提交事项操作</GlassButton></section>
    </div>
    <ActionEditor ref="actionEditor" @saved="changed" />
    <el-dialog class="customer-hub-dialog" v-model="feedbackVisible" append-to-body title="产物反馈" width="640px"><el-alert v-if="error" :title="error" type="error" :closable="false" /><GlassButton variant="secondary" :loading="loading" @click="load">刷新产物状态</GlassButton><el-form label-position="top" :disabled="saving"><el-form-item label="评价维度"><el-select v-model="feedback.dimension"><el-option v-for="(label,key) in FEEDBACK_DIMENSIONS" :key="key" :label="label" :value="key" /></el-select></el-form-item><el-form-item label="判断"><el-radio-group v-model="feedback.decision"><el-radio value="yes">是</el-radio><el-radio value="no">否</el-radio></el-radio-group></el-form-item><el-form-item label="理由或真实采纳依据"><el-input v-model="feedback.reason" type="textarea" /></el-form-item><EvidencePicker v-if="item" v-model="feedback.evidence_refs" :customer-id="item.customer_id" kind="event" references :disabled="saving" /></el-form><template #footer><GlassButton v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="primary" :loading="saving" :disabled="feedback.dimension === 'adoption' && feedback.decision === 'yes' && (!feedbackTarget?.can_adopt || !feedback.evidence_refs.length)" @click="saveFeedback">保存这个维度</GlassButton></template></el-dialog>
    <el-dialog class="customer-hub-dialog" v-model="delegationDialog" append-to-body title="委派状态变更" width="480px"><el-alert v-if="error" :title="error" type="error" :closable="false" /><GlassButton variant="secondary" :loading="loading" @click="load">刷新委派状态（保留原因）</GlassButton><p>{{ delegationOperation }} · {{ selectedDelegation?.goal }}</p><el-input v-model="delegationReason" type="textarea" placeholder="填写原因" /><template #footer><GlassButton v-any-permission="['customer_pcw:write','customer_radar:write','customer:admin']" variant="primary" :loading="saving" :disabled="!delegationReason.trim()" @click="changeDelegation">确认状态变更</GlassButton></template></el-dialog>
  </DetailDrawer>
</template>
<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { getWorkItem, transitionWorkItem, createWorkItemDelegation, transitionDelegation, submitWorkItemFeedback } from '@/api/customerHub'
import { formatBeijingDateTime } from '@/utils/datetime'
import { msgSuccess } from '@/utils/feedback'
import { readableValue } from './operationsPresentation'
import { availableItemOperations, buildItemTransition, createSubmissionIdentity, errorMessage, ITEM_STATE_LABELS, ITEM_OPERATION_LABELS, FEEDBACK_DIMENSIONS, DELEGATION_STATE_LABELS, RUN_STATE_LABELS } from './workbenchV2Controller'
import EvidencePicker from './EvidencePicker.vue'
import ActionEditor from './ActionEditor.vue'
const emit = defineEmits(['saved'])
const visible = ref(false), loading = ref(false), saving = ref(false), item = ref(null), error = ref(''), actionEditor = ref(null), operation = ref(''), evidenceKind = ref('event'), delegationGoal = ref('')
const form = reactive({ reason:'', resume_condition:'', waiting_kind:'customer', review_at:'', evidence_refs:[], cancel_remaining:false, delivery_decision:'', delivery_plan:'', customer_decision:'' })
const identity = createSubmissionIdentity('item'), delegationIdentity = createSubmissionIdentity('delegation'), feedbackIdentity = createSubmissionIdentity('feedback')
const feedbackVisible = ref(false), feedbackTarget = ref(null), feedback = reactive({dimension:'accuracy',decision:'yes',reason:'',evidence_refs:[]})
const delegationDialog = ref(false), selectedDelegation = ref(null), delegationOperation = ref(''), delegationReason = ref('')
const operations = computed(() => availableItemOperations(item.value))
watch(operation, value => { form.evidence_refs = []; evidenceKind.value = value === 'record_delivery_plan' ? 'message' : 'event' })
const date = value => value ? formatBeijingDateTime(value, {seconds:false}) : '未提供'
let latestLoad = 0, itemId = null
async function open(row) { if (saving.value) return; itemId = row.item_id; item.value = null; operation.value = ''; Object.assign(form,{reason:'',resume_condition:'',waiting_kind:'customer',review_at:'',evidence_refs:[],cancel_remaining:false,delivery_decision:'',delivery_plan:'',customer_decision:''}); identity.reset(); delegationIdentity.reset(); feedbackIdentity.reset(); delegationGoal.value=''; visible.value=true; await load() }
async function load() { const request=++latestLoad; loading.value=true; error.value=''; try { const response=await getWorkItem(itemId); if(request===latestLoad) { item.value=response.data; if(selectedDelegation.value)selectedDelegation.value=item.value.delegations?.find(row=>row.id===selectedDelegation.value.id) || selectedDelegation.value } } catch(e) {if(request===latestLoad) error.value=errorMessage(e)} finally{if(request===latestLoad)loading.value=false} }
async function mutate(request, message) { if(saving.value)return false; saving.value=true;error.value='';try { await request();msgSuccess(message);emit('saved');await load();return true }catch(e){error.value=errorMessage(e);return false}finally{saving.value=false} }
async function transition() {try {const payload=buildItemTransition(item.value,operation.value,form);if(await mutate(()=>transitionWorkItem(item.value.item_id,payload,identity.forPayload(payload)),'事项状态已保存')) operation.value=''}catch(e){error.value=errorMessage(e)} }
async function delegate() {const payload={goal:delegationGoal.value.trim(),scope:'prepare',expected_item_version:item.value.row_version};if(await mutate(()=>createWorkItemDelegation(item.value.item_id,payload,delegationIdentity.forPayload(payload)),'委派已登记，请核对实际运行状态'))delegationGoal.value=''}
function openFeedback(artifact){feedbackTarget.value=artifact;Object.assign(feedback,{dimension:'accuracy',decision:'yes',reason:'',evidence_refs:[]});feedbackIdentity.reset();feedbackVisible.value=true}
async function saveFeedback(){const payload={target_id:feedbackTarget.value.target_id,target_revision:feedbackTarget.value.target_revision,...feedback};if(await mutate(()=>submitWorkItemFeedback(item.value.item_id,payload,feedbackIdentity.forPayload(payload)),'该维度反馈已记录'))feedbackVisible.value=false}
function openDelegationOperation(row,op){selectedDelegation.value=row;delegationOperation.value=op;delegationReason.value='';delegationIdentity.reset();delegationDialog.value=true}
async function changeDelegation(){const payload={operation:delegationOperation.value,expected_delegation_version:selectedDelegation.value.row_version,reason:delegationReason.value.trim()};if(await mutate(()=>transitionDelegation(selectedDelegation.value.id,payload,delegationIdentity.forPayload(payload)),'委派状态已登记，请核对在途执行回执'))delegationDialog.value=false}
async function changed(){emit('saved');await load()}
function beforeClose(done){if(!saving.value)done()}
defineExpose({open})
</script>
<style scoped>
.item-detail{display:grid;gap:16px;padding-top:16px;color:var(--text-primary)}h2{font-size:17px;margin:0}h3{font-size:14px;margin:0 0 10px}section{border:1px solid var(--border-color);border-radius:var(--card-radius);padding:14px}p{line-height:1.6;color:var(--text-secondary);overflow-wrap:anywhere}article{padding:10px 0;border-bottom:1px solid var(--border-color)}article:last-child{border-bottom:0}.warning{color:var(--color-warning-text)}.operation-buttons{display:flex;flex-wrap:wrap;gap:8px}.el-select,.el-date-editor{max-width:100%}a{color: var(--color-primary-text)}
</style>
