import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
const [origin, modulePath, executablePath, output] = process.argv.slice(2)
assert.match(origin, /^http:\/\/127\.0\.0\.1:\d+$/)
let input = ''; for await (const chunk of process.stdin) input += chunk.toString('utf8')
const seed = JSON.parse(input); input = ''; assert.equal(typeof seed.readonlyPrice, 'boolean')
const { chromium, request } = createRequire(import.meta.url)(modulePath)
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ executablePath, headless: true })
const contexts = [], errors = [], scenarios = []
const api = origin + '/api/portal/v1', admin = origin + '/api/portal/admin/v1'
async function data(response, status = 200) {
 assert.equal(response.status(), status, 'Unexpected response: ' + new URL(response.url()).pathname)
 const body = await response.json(); assert.equal(body.code, status); return body.data
}
try {
 const employee = await request.newContext({ baseURL: origin }); contexts.push(employee)
 const auth = await employee.post('/api/auth/login', { data: { username: seed.rootUsername, password: seed.password } })
 assert.equal(auth.status(), 200); const employeeToken = (await auth.json()).access_token
 const configured = await data(await employee.patch(admin + '/customers/' + seed.accessId, { headers: { Authorization: 'Bearer ' + employeeToken, 'If-Match': '"' + seed.accessVersion + '"' }, data: {
  status: 'enabled', capabilities: { can_order: false, can_view_price: seed.readonlyPrice }, reason: 'Owned browser read-only access verification' } }))
 assert.equal(configured.status, 'enabled'); assert.equal(configured.capabilities.can_order, false)
 const context = await browser.newContext({ viewport: { width: 320, height: 1000 } }); contexts.push(context)
 const page = await context.newPage(); page.on('pageerror', problem => errors.push(problem.name))
 const financialPosts = []; page.on('request', event => { const path = new URL(event.url()).pathname; if (event.method() === 'POST' && (path === '/api/portal/v1/orders' || path === '/api/portal/v1/quotes')) financialPosts.push(path) })
 await page.goto(origin + '/collection')
 await page.getByLabel('Email address', { exact: true }).fill(seed.buyerEmail)
 const challengeResponse = page.waitForResponse(response => response.url() === api + '/auth/challenges' && response.request().method() === 'POST')
 await page.getByRole('button', { name: /Continue with email/ }).click()
 const challenge = await data(await challengeResponse, 202)
 const codeResponse = await context.request.get(origin + '/__owned/otp/' + challenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
 assert.equal(codeResponse.status(), 200); const code = (await codeResponse.json()).code; assert.match(code, /^[0-9]{6}$/)
 await page.getByLabel('Verification code', { exact: true }).fill(code)
 const verifyResponse = page.waitForResponse(response => response.url() === api + '/auth/verify' && response.request().method() === 'POST')
 const catalogResponse = page.waitForResponse(response => response.url().split('?')[0] === api + '/catalog' && response.request().method() === 'GET')
 await page.getByRole('button', { name: /Enter your collection/ }).click(); await data(await verifyResponse)
 const catalog = await data(await catalogResponse)
 assert.equal(catalog.items.length, 1); assert.equal(catalog.items[0].item_id, seed.itemId)
 assert.equal(Object.hasOwn(catalog.items[0], 'unit_price'), seed.readonlyPrice)
 const session = await data(await context.request.get(api + '/session'))
 assert.equal(session.capabilities.place_order, false); assert.equal(session.capabilities.view_price, seed.readonlyPrice)
 await page.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true }).waitFor()
 assert.equal(await page.getByRole('link', { name: /Selection/ }).count(), 0)
 await page.getByText('Your access is for browsing. Contact your representative to request ordering access.', { exact: true }).waitFor()
 assert.equal(await page.getByText('Your pricing · USD', { exact: true }).count(), Number(seed.readonlyPrice))
 scenarios.push('actual current Ark read-only settings govern the authenticated catalog and visible navigation')
 const detail = await data(await context.request.get(api + '/catalog/' + seed.itemId))
 await page.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true }).click()
 assert.equal(Object.hasOwn(detail, 'unit_price'), seed.readonlyPrice)
 const dialog = page.getByRole('dialog', { name: seed.standardModel, exact: true })
 await dialog.waitFor(); assert.equal(await dialog.getByRole('button', { name: 'Add to selection', exact: true }).count(), 0)
 assert.equal(await dialog.locator('.detail-price').count(), Number(seed.readonlyPrice))
 await dialog.getByRole('button', { name: 'Back to collection', exact: true }).click()
 scenarios.push('product detail has no ordering affordance and omits hidden price in actual API and DOM')
 for (const width of [1440, 390, 320]) {
  await page.setViewportSize({ width, height: 1000 })
  await page.goto(origin + '/checkout')
  await page.getByRole('heading', { name: 'Collection access only.', exact: true }).waitFor()
  await page.getByRole('heading', { name: 'Your collection.', level: 1, exact: true }).waitFor()
  assert.equal(await page.getByRole('link', { name: /Selection/ }).count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Review request', exact: true }).count(), 0)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false)
  await page.screenshot({ path: output + '/actual-readonly-checkout-' + width + '.png', animations: 'disabled' })
 }
 scenarios.push('direct checkout shows an honest browse-only state at desktop and mobile widths')
 const forbidden = await context.request.post(api + '/quotes', { headers: { Origin: origin, 'X-Portal-CSRF': session.csrf_token }, data: {
  items: [{ item_id: seed.itemId, quantity: 1 }], delivery: { contact_name: 'Scoped buyer', phone: '+44 10000000', address_line1: '20 Example Street', city: 'London', country_code: 'GB' } } })
 assert.equal(forbidden.status(), 403); assert.equal((await forbidden.json()).data.error_code, 'ACTION_FORBIDDEN')
 scenarios.push('manual authenticated quote POST is denied by the actual server, independently of hidden controls')
 // A key-only simulated refresh marker; never reconstruct a POST body or claim an ACK fault.
 const recoveryKey = randomUUID(), marker = JSON.stringify({ key: recoveryKey })
 await page.evaluate(({ account, marker }) => sessionStorage.setItem('leshine.portal.pending:' + account, marker), { account: seed.buyerAccountPublicId, marker })
 const beforeRecoveryPosts = financialPosts.length
 await page.reload()
 await page.getByRole('heading', { name: 'Let’s confirm the result.', exact: true }).waitFor()
 await page.getByRole('heading', { name: 'Your selection.', level: 1, exact: true }).waitFor()
 assert.equal(await page.getByRole('heading', { name: 'Collection access only.', exact: true }).count(), 0)
 await page.getByText('Reference: ' + recoveryKey, { exact: true }).waitFor()
 assert.equal(await page.getByRole('button', { name: 'Retry original request', exact: true }).count(), 0)
 const lookup = page.waitForResponse(response => response.url() === api + '/orders/by-key/' + recoveryKey && response.request().method() === 'GET')
 await page.getByRole('button', { name: 'Check request status', exact: true }).click()
 const lookupResponse = await lookup
 assert.equal(lookupResponse.status(), 404)
 assert.equal(await lookupResponse.finished(), null)
 await page.getByRole('button', { name: 'Check request status', exact: true }).waitFor()
 await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
 await page.getByRole('heading', { name: 'Let’s confirm the result.', exact: true }).waitFor()
 assert.equal(await page.evaluate(account => sessionStorage.getItem('leshine.portal.pending:' + account), seed.buyerAccountPublicId), marker)
 assert.equal(financialPosts.length, beforeRecoveryPosts)
 await page.screenshot({ path: output + '/actual-readonly-recovery-320.png', animations: 'disabled' })
 scenarios.push('read-only refresh preserves the simulated key-only recovery marker and GET404 cannot authorize another POST')
 const listingResponse = page.waitForResponse(response => response.url().split('?')[0] === api + '/orders' && response.request().method() === 'GET')
 await page.getByRole('link', { name: 'Requests', exact: true }).click()
 const listing = await data(await listingResponse)
 assert.ok(listing.items.some(item => item.request_id === seed.historyRequestId))
 const historical = page.locator('a[href="/orders/' + seed.historyRequestId + '"]')
 await historical.waitFor()
 assert.equal(await page.locator('.order-list-amount').count(), Number(seed.readonlyPrice))
 const historyResponse = page.waitForResponse(response => response.url() === api + '/orders/' + seed.historyRequestId && response.request().method() === 'GET')
 await historical.click(); const history = await data(await historyResponse)
 assert.equal(history.request_id, seed.historyRequestId); assert.equal(history.request_no, seed.historyRequestNo)
 assert.deepEqual(history.available_actions, [])
 assert.equal(Object.hasOwn(history, 'product_amount'), seed.readonlyPrice)
 assert.equal(Object.hasOwn(history.items[0], 'unit_price'), seed.readonlyPrice)
 await page.getByRole('heading', { name: 'Request details', level: 2, exact: true }).waitFor()
 assert.equal(await page.locator('.quote-totals').count(), Number(seed.readonlyPrice))
 assert.equal(await page.locator('.order-secondary-actions button').count(), 0)
 assert.equal(await page.evaluate(account => sessionStorage.getItem('leshine.portal.pending:' + account), seed.buyerAccountPublicId), marker)
 assert.equal(financialPosts.length, beforeRecoveryPosts)
 await page.screenshot({ path: output + '/actual-readonly-history-320.png', animations: 'disabled' })
 scenarios.push('actual same-company historical request stays readable with current price masking, no action buttons and unchanged recovery marker')
 assert.deepEqual(errors, [])
 await writeFile(output + '/report.json', JSON.stringify({ status: 'pass', viewPrice: seed.readonlyPrice, apiInterceptions: 0, widths: [1440,390,320], scenarios, scope: 'Actual current Ark API configuration, OTP and read-only UI; owned MySQL, controlled upstream, not production' }, null, 2))
 console.log(JSON.stringify({ status: 'pass', scenarioGroups: scenarios.length, apiInterceptions: 0 }))
} finally { await Promise.all(contexts.map(context => context.dispose ? context.dispose() : context.close())); await browser.close() }
