import assert from 'node:assert/strict'
import { createBrowserInteraction } from './keyboardInteraction.mjs'
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const [origin, modulePath, executablePath, output] = process.argv.slice(2)
assert.match(origin, /^http:\/\/127\.0\.0\.1:\d+$/)
assert.ok(modulePath && executablePath && output)
let privateInput = ''
for await (const chunk of process.stdin) privateInput += chunk.toString('utf8')
const seed = JSON.parse(privateInput)
privateInput = ''
const { chromium, request } = createRequire(import.meta.url)(modulePath)
await mkdir(output, { recursive: true })
const interaction = createBrowserInteraction(seed.interactionMode || 'pointer', output)
const baseWidth = seed.interactionMode === 'keyboard' ? 320 : 1440
const browser = await chromium.launch({ executablePath, headless: true })
const contexts = [], employees = [], errors = [], observed = [], scenarios = []
const buyer = await browser.newContext({ viewport: { width: baseWidth, height: 1000 }, acceptDownloads: true })
contexts.push(buyer)
const page = await buyer.newPage()
function watch(page) {
 page.on('pageerror', error => errors.push(error.message))
 page.on('request', event => {
  const path = new URL(event.url()).pathname
  if (path.startsWith('/api/')) observed.push({ path, method: event.method() })
 })
}
watch(page)
const api = origin + '/api/portal/v1', admin = origin + '/api/portal/admin/v1'
async function data(response, expected = 200) {
 assert.equal(response.status(), expected, 'Unexpected status: ' + new URL(response.url()).pathname)
 const result = await response.json()
 assert.equal(result.code, expected)
 return result.data
}
async function loginEmployee(username) {
 const context = await request.newContext({ baseURL: origin })
 employees.push(context)
 const response = await context.post('/api/auth/login', { data: { username, password: seed.password } })
 assert.equal(response.status(), 200, 'Actual employee login failed')
 const result = await response.json()
 assert.equal(typeof result.access_token, 'string')
 return { context, headers: { Authorization: 'Bearer ' + result.access_token } }
}
async function employeePage(username, id = null) {
 const context = await browser.newContext({ viewport: { width: baseWidth, height: 1000 } })
 contexts.push(context)
 const page = await context.newPage(); watch(page)
 await page.goto(origin + (id ? '/portal/orders?request=' + id : '/portal/customers'))
 await interaction.fill(page.getByLabel('用户名', { exact: true }), username, 'trade-step-50')
 await interaction.fill(page.getByLabel('密码', { exact: true }), seed.password, 'trade-step-51')
 const loggedIn = page.waitForResponse(response => response.url().endsWith('/api/auth/login') && response.request().method() === 'POST')
 await interaction.click(page.locator('button[type="submit"]'), 'trade-step-53')
 assert.equal((await loggedIn).status(), 200, 'Actual Chinese employee UI login failed')
 await page.locator('.portal-heading').getByRole('heading', { name: id ? '客户下单请求' : '客户访问与采购账号', exact: true }).waitFor()
 return { context, page }
}
async function employeeGeometry(page, dialog, label) {
 for (const width of [1440, 390, 320]) {
  await page.setViewportSize({ width, height: 1000 })
  if (await dialog.locator('.el-checkbox').count()) await dialog.locator('.el-checkbox').scrollIntoViewIfNeeded()
  assert.equal(await dialog.evaluate(element => element.scrollWidth > element.clientWidth + 1), false, label + ' must fit width ' + width)
  await dialog.screenshot({ path: output + '/' + label + '-' + width + '.png', animations: 'disabled' })
 }
 await page.setViewportSize({ width: baseWidth, height: 1000 })
}
async function openMapping(page) {
 await page.goto(origin + '/portal/customers')
 await interaction.click(page.locator('button[data-portal-access="' + seed.accessId + '"]'), 'trade-step-69')
 await interaction.click(page.getByRole('button', { name: '型号颜色映射', exact: true }), 'trade-step-70')
 const dialog = page.locator('.portal-mapping-dialog:visible')
 await dialog.getByRole('button', { name: '校验并预览', exact: true }).waitFor()
 return dialog
}
async function addMapping(page, dialog, kind, source) {
 // Element Plus hides the non-filterable select input; use its visible wrapper.
 await interaction.click(dialog.locator('.mapping-add .el-form-item').filter({ hasText: '映射类型' }).locator('.el-select__wrapper'), 'trade-step-77')
 await interaction.click(page.getByRole('option', { name: kind, exact: true }), 'trade-step-78')
 await interaction.click(dialog.locator('.mapping-add .el-form-item').filter({ hasText: '标准来源' }).locator('.el-select__wrapper'), 'trade-step-79')
 await interaction.fill(dialog.getByRole('combobox', { name: '标准来源', exact: true }), source, 'trade-step-80')
 await interaction.click(page.getByRole('option').filter({ hasText: source }), 'trade-step-81')
 await interaction.click(dialog.getByRole('button', { name: '添加映射', exact: true }), 'trade-step-82')
}
async function publishMapping(page, dialog, baseVersion, model, color, sku, label) {
 const path = admin + '/customers/' + seed.accessId + '/mapping'
 const previewed = page.waitForResponse(response => response.url().endsWith(path + '/preview') && response.request().method() === 'POST')
 await interaction.click(dialog.getByRole('button', { name: '校验并预览', exact: true }), 'trade-step-87')
 const preview = await data(await previewed)
 assert.equal(preview.access_id, seed.accessId); assert.equal(preview.base_version, baseVersion)
 assert.equal(preview.valid, true); assert.deepEqual(preview.conflicts, [])
 assert.ok(preview.items.some(item => item.item_id === seed.itemId && item.model_name === model && item.color_name === color && item.customer_sku === sku))
 await dialog.getByRole('heading', { name: '版本差异 · 已发布 v' + baseVersion + ' → 待发布 v' + (baseVersion + 1), exact: true }).waitFor()
 assert.equal(await dialog.getByRole('button', { name: '发布映射', exact: true }).isDisabled(), true)
 await employeeGeometry(page, dialog, label)
 await interaction.click(dialog.locator('.el-checkbox').filter({ hasText: '我已核对完整展示效果' }), 'trade-step-95')
 assert.equal(await dialog.getByRole('checkbox').isChecked(), true)
 const published = page.waitForResponse(response => response.url().endsWith(path + '/publish') && response.request().method() === 'POST')
 await interaction.click(dialog.getByRole('button', { name: '发布映射', exact: true }), 'trade-step-98')
 const response = await published
 const body = response.request().postDataJSON()
 assert.equal(body.base_version, baseVersion)
 assert.equal(response.request().headers()['if-match'], '"' + preview.row_version + '"')
 assert.ok(body.entries.some(item => item.kind === 'sku' && item.source_key === seed.itemId && item.item_id === seed.itemId && item.display_value === model && item.customer_sku === sku))
 assert.ok(body.entries.some(item => item.kind === 'color' && item.source_key === seed.standardColorKey && item.display_value === color))
 const receipt = await data(response, 201)
 assert.equal(receipt.mapping_version, baseVersion + 1)
 await dialog.waitFor({ state: 'hidden' })
 return receipt
}
async function inviteAndActivate() {
 const administrator = await employeePage(seed.rootUsername)
 await interaction.click(administrator.page.locator('button[data-portal-access="' + seed.accessId + '"]'), 'trade-step-112')
 await interaction.click(administrator.page.locator('button[data-portal-action="invite"]').filter({ hasText: '邀请采购账号' }), 'trade-step-113')
 const dialog = administrator.page.locator('.portal-access-action:visible')
 await interaction.fill(dialog.getByRole('textbox', { name: '采购邮箱', exact: true }), seed.invitedBuyerEmail, 'trade-step-115')
 await interaction.fill(dialog.getByRole('textbox', { name: '采购联系人', exact: true }), 'Invited colleague', 'trade-step-116')
 assert.equal(await dialog.getByRole('button', { name: '确认操作', exact: true }).isDisabled(), true)
 await employeeGeometry(administrator.page, dialog, 'actual-main-invite-account')
 await interaction.click(dialog.locator('.el-checkbox').filter({ hasText: '我已核对客户与影响' }), 'trade-step-119')
 const created = administrator.page.waitForResponse(response => response.url() === admin + '/customers/' + seed.accessId + '/invitations' && response.request().method() === 'POST')
 await interaction.click(dialog.getByRole('button', { name: '确认操作', exact: true }), 'trade-step-121')
 const response = await created
 assert.ok(response.request().headers()['idempotency-key'])
 assert.deepEqual(response.request().postDataJSON(), { email: seed.invitedBuyerEmail, contact_name: 'Invited colleague' })
 const receipt = await data(response, 201)
 assert.equal(receipt.replayed, false)
 await dialog.waitFor({ state: 'hidden' })
 scenarios.push('actual Chinese admin UI explicitly creates a queued invitation, not mail delivery')
 const context = await browser.newContext({ viewport: { width: 390, height: 1000 } }); contexts.push(context)
 const invitedPage = await context.newPage(); watch(invitedPage)
 async function mailbox() {
  const response = await context.request.get(origin + '/__owned/invitation/' + receipt.invitation_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
  assert.equal(response.status(), 200)
  return response.json()
 }
 const invitation = await mailbox()
 for (const suffix of ['#token=', '?token=']) {
  const before = observed.length
  await invitedPage.goto(origin + '/activate' + suffix + encodeURIComponent(invitation.token))
  await invitedPage.getByText('YOUR INVITATION', { exact: true }).waitFor()
  await invitedPage.waitForLoadState('networkidle')
  assert.equal(invitedPage.url(), origin + '/activate')
  assert.equal(observed.length, before)
  assert.equal((await context.cookies(origin)).filter(cookie => cookie.name === 'dev-portal_session').length, 0)
 }
 assert.equal((await mailbox()).accountPublicId, invitation.accountPublicId)
 scenarios.push('opening hash/query invitation links strips secrets without consuming or activating')
 // A forwarded link plus another email yields the generic challenge, not access.
 const wrong = await browser.newContext(); contexts.push(wrong)
 const wrongPage = await wrong.newPage(); watch(wrongPage)
 await wrongPage.goto(origin + '/activate#token=' + encodeURIComponent(invitation.token))
 await interaction.fill(wrongPage.getByLabel('Email address', { exact: true }), seed.forwardedBuyerEmail, 'trade-step-152')
 const wrongChallenge = wrongPage.waitForResponse(response => response.url() === api + '/auth/challenges' && response.request().method() === 'POST')
 await interaction.click(wrongPage.getByRole('button', { name: /Continue with email/ }), 'trade-step-154')
 const rejectedChallenge = await data(await wrongChallenge, 202)
 assert.equal((await wrong.request.get(origin + '/__owned/otp/' + rejectedChallenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })).status(), 404)
 assert.equal((await wrong.request.get(api + '/session')).status(), 401)
 assert.equal((await mailbox()).accountPublicId, invitation.accountPublicId)
 scenarios.push('forwarded invitation with an already active foreign-company email cannot obtain an OTP or session')
 await interaction.fill(invitedPage.getByLabel('Email address', { exact: true }), seed.invitedBuyerEmail, 'trade-step-160')
 const challenged = invitedPage.waitForResponse(response => response.url() === api + '/auth/challenges' && response.request().method() === 'POST')
 await interaction.click(invitedPage.getByRole('button', { name: /Continue with email/ }), 'trade-step-162')
 const challengeResponse = await challenged
 assert.equal(challengeResponse.request().postDataJSON().purpose, 'activate')
 const challenge = await data(challengeResponse, 202)
 const codeResponse = await context.request.get(origin + '/__owned/otp/' + challenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
 assert.equal(codeResponse.status(), 200)
 const { code } = await codeResponse.json(); assert.match(code, /^[0-9]{6}$/)
 await interaction.fill(invitedPage.getByLabel('Verification code', { exact: true }), code, 'trade-step-169')
 const verified = invitedPage.waitForResponse(response => response.url() === api + '/auth/verify' && response.request().method() === 'POST')
 const catalogued = invitedPage.waitForResponse(response => response.url().split('?')[0] === api + '/catalog' && response.request().method() === 'GET')
 await interaction.click(invitedPage.getByRole('button', { name: /Activate your access/ }), 'trade-step-172')
 await data(await verified)
 const catalog = await data(await catalogued)
 assert.ok(catalog.items.some(item => item.item_id === seed.itemId && item.model_name === seed.standardModel && item.color_name === seed.standardColor))
 await invitedPage.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true }).waitFor()
 const cookies = await context.cookies(origin), session = cookies.find(cookie => cookie.name === 'dev-portal_session')
 assert.ok(session?.httpOnly && session.sameSite === 'Lax')
 assert.equal((await context.request.get(origin + '/__owned/invitation/' + receipt.invitation_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })).status(), 404)
 scenarios.push('actual invited email OTP activates one account and its scoped catalog')
 return { administrator, context, page: invitedPage, accountId: invitation.accountPublicId, rejectedChallengeId: rejectedChallenge.challenge_id }
}
async function signIn(context, page, email) {
 await page.goto(origin + '/collection')
 await interaction.fill(page.getByLabel('Email address', { exact: true }), email, 'trade-step-185')
 const challenged = page.waitForResponse(response => response.url().endsWith('/auth/challenges') && response.request().method() === 'POST')
 await interaction.click(page.getByRole('button', { name: /Continue with email/ }), 'trade-step-187')
 const challenge = await data(await challenged, 202)
 const codeResponse = await context.request.get(origin + '/__owned/otp/' + challenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
 assert.equal(codeResponse.status(), 200, 'Owned mailbox evidence unavailable')
 const { code } = await codeResponse.json()
 assert.match(code, /^[0-9]{6}$/)
 await interaction.fill(page.getByLabel('Verification code', { exact: true }), code, 'trade-step-193')
 const verified = page.waitForResponse(response => response.url().endsWith('/auth/verify') && response.request().method() === 'POST')
 await interaction.click(page.getByRole('button', { name: /Enter your collection/ }), 'trade-step-195')
 await data(await verified)
 await page.locator('.portal-shell').waitFor()
 const cookies = await context.cookies(origin)
 const current = cookies.find(cookie => cookie.name === 'dev-portal_session')
 assert.ok(current?.httpOnly && current.sameSite === 'Lax')
}
async function geometry(label) {
 for (const width of [1440, 390, 320]) {
  await page.setViewportSize({ width, height: 1000 })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, label + ' must fit width ' + width)
  await page.screenshot({ path: output + '/' + label + '-' + width + '.png', fullPage: true })
 }
}
try {
 const owner = await loginEmployee(seed.ownerUsername), other = await loginEmployee(seed.otherUsername), root = await loginEmployee(seed.rootUsername)
 const invited = await inviteAndActivate()
 const entries = [{ kind: 'sku', source_key: seed.itemId, item_id: seed.itemId, display_value: 'Buyer Signature Straight', customer_sku: 'BUYER-ST-20' },
  { kind: 'color', source_key: seed.standardColorKey, display_value: 'Buyer Natural Black' }]
 const mappingEditor = await employeePage(seed.ownerUsername)
 let mapping = await openMapping(mappingEditor.page)
 await addMapping(mappingEditor.page, mapping, '单规格型号名 / 客户货号', seed.itemId)
 const initialSku = mapping.locator('.mapping-entry').filter({ hasText: '单规格型号名 / 客户货号' })
 await interaction.fill(initialSku.getByRole('textbox', { name: /^客户展示名 / }), 'Buyer Signature Straight', 'trade-step-218')
 await interaction.fill(initialSku.getByRole('textbox', { name: /^客户货号 / }), 'BUYER-ST-20', 'trade-step-219')
 await addMapping(mappingEditor.page, mapping, '颜色别名', seed.standardColorKey)
 await interaction.fill(mapping.locator('.mapping-entry').filter({ hasText: '颜色别名' }).getByRole('textbox', { name: /^客户展示名 / }), 'Buyer Natural Black', 'trade-step-221')
 const mapped = await publishMapping(mappingEditor.page, mapping, 0, 'Buyer Signature Straight', 'Buyer Natural Black', 'BUYER-ST-20', 'actual-main-mapping-first')
 assert.equal(mapped.mapping_version, 1); assert.ok(mapped.row_version > seed.accessVersion)
 scenarios.push('actual Chinese employee UI adds canonical SKU and color aliases, previews and publishes')
 await signIn(buyer, page, seed.buyerEmail)
 await interaction.click(page.getByRole('button', { name: 'View Buyer Signature Straight, Buyer Natural Black', exact: true }), 'trade-step-226')
 await interaction.fill(page.getByRole('dialog').getByLabel('Quantity', { exact: true }), '3', 'trade-step-227')
 await interaction.click(page.getByRole('button', { name: 'Add to selection', exact: true }), 'trade-step-228')
 await interaction.click(page.getByRole('button', { name: 'Review selection', exact: true }), 'trade-step-229')
 const delivery = { contact_name: 'Owned Buyer', phone: '+44 10000000', address_line1: '10 Example Street', city: 'London', country_code: 'GB' }
 for (const [label, value] of Object.entries({ 'Contact name': delivery.contact_name, 'Phone number': delivery.phone, 'Address line 1': delivery.address_line1, City: delivery.city })) await interaction.fill(page.getByLabel(label, { exact: true }), value, 'trade-step-231')
 await interaction.fill(page.getByLabel('Country code (e.g. US, GB)', { exact: true }), 'GB', 'trade-step-232')
 await interaction.fill(page.getByLabel('Your PO / reference (optional)', { exact: true }), 'PO-OWNED-BROWSER', 'trade-step-233')
 await interaction.click(page.getByRole('button', { name: 'Review request', exact: true }), 'trade-step-234')
 const submit = page.getByRole('button', { name: 'Submit order request', exact: true })
 await submit.waitFor(); assert.equal(await submit.isDisabled(), true)
 assert.match(await page.getByRole('complementary', { name: 'Server review' }).innerText(), /81\.00/)
 await interaction.check(page.getByRole('checkbox'), 'trade-step-238')
 const submitted = page.waitForResponse(response => response.url() === api + '/orders' && response.request().method() === 'POST')
 await interaction.click(submit, 'trade-step-240')
 const result = await data(await submitted, 201), id = result.request_id
 assert.equal(result.status, 'submitted'); assert.equal(result.total_amount, null)
 await interaction.click(page.getByRole('button', { name: 'View request', exact: true }), 'trade-step-243')
 await page.getByRole('button', { name: 'Refresh details', exact: true }).waitFor()
 scenarios.push('actual customer OTP and cookie submit explicit server quote')
 const salesperson = await employeePage(seed.ownerUsername, id), staffPage = salesperson.page
 await interaction.click(staffPage.getByRole('button', { name: '处理请求', exact: true }), 'trade-step-247')
 const staffReview = staffPage.getByRole('dialog', { name: '处理客户下单请求', exact: true })
 await staffReview.getByText('当前版本完整条款', { exact: true }).waitFor()
 await interaction.click(staffReview.locator('.el-radio-button').filter({ hasText: '发送确认提案' }), 'trade-step-250')
 for (const [label, value] of Object.entries({ '运费（USD）': '45.00', '包装费（USD）': '2.00', '附加费（USD）': '0.00' })) await interaction.fill(staffReview.getByLabel(label, { exact: true }), value, 'trade-step-251')
 await interaction.fill(staffReview.getByLabel('操作原因', { exact: true }), 'Confirmed complete owned order terms', 'trade-step-252')
 const previewed = staffPage.waitForResponse(response => response.url().endsWith('/orders/' + id + '/proposal-preview') && response.request().method() === 'POST')
 await interaction.click(staffReview.getByRole('button', { name: '预览金额与变化', exact: true }), 'trade-step-254')
 await data(await previewed)
 await staffReview.getByText('128.00', { exact: false }).first().waitFor()
 await employeeGeometry(staffPage, staffReview, 'actual-main-employee-proposal')
 await interaction.click(staffReview.locator('.el-checkbox').filter({ hasText: '我已核对内容，确认发送确认提案' }), 'trade-step-258')
 assert.equal(await staffReview.getByRole('checkbox').isChecked(), true)
 const proposedResponse = staffPage.waitForResponse(response => response.url().endsWith('/orders/' + id + '/proposals') && response.request().method() === 'POST')
 await interaction.click(staffReview.getByRole('button', { name: '确认操作', exact: true }), 'trade-step-261')
 const proposed = await data(await proposedResponse)
 await staffReview.waitFor({ state: 'hidden' })
 scenarios.push('actual Chinese employee UI previews and submits complete customer proposal')
 const outsider = await employeePage(seed.otherUsername, id)
 await outsider.page.getByText('请求不存在或已不在当前授权范围内。', { exact: true }).waitFor()
 assert.equal(await outsider.page.getByRole('button', { name: '处理请求', exact: true }).count(), 0)
 assert.equal(await outsider.page.locator('.el-table__body tbody tr').count(), 0)
 assert.ok(!(await outsider.page.locator('body').innerText()).includes('Buyer Signature Straight'))
 scenarios.push('other Chinese employee UI cannot list or inspect the private request')
 const approval = { accepted_revision_id: proposed.original_receipt.revision_id }, expectedBeforeAccept = proposed.row_version
 const premature = await owner.context.post(admin + '/orders/' + id + '/approve', { headers: { ...owner.headers, 'If-Match': '"' + expectedBeforeAccept + '"' }, data: approval })
 assert.equal(premature.status(), 409)
 assert.equal((await premature.json()).data.error_code, 'CUSTOMER_ACCEPTANCE_REQUIRED')
 assert.equal((await other.context.get(admin + '/orders/' + id, { headers: other.headers })).status(), 404)
 assert.equal((await other.context.post(admin + '/orders/' + id + '/approve', { headers: { ...other.headers, 'If-Match': '"' + expectedBeforeAccept + '"' }, data: approval })).status(), 404)
 scenarios.push('current sales scope and customer acceptance prerequisite')
 await interaction.click(page.getByRole('button', { name: 'Refresh details', exact: true }), 'trade-step-278')
 await page.getByRole('button', { name: 'Review and accept proposal', exact: true }).waitFor()
 assert.match(await page.locator('.proposal-panel').innerText(), /128\.00/)
 await geometry('actual-main-proposal')
 const armed = await buyer.request.post(origin + '/__owned/control', { headers: { 'X-Owned-Broker': seed.brokerKey }, data: { fault: 'accept_ack' } })
 assert.equal(armed.status(), 200)
 await interaction.click(page.getByRole('button', { name: 'Review and accept proposal', exact: true }), 'trade-step-284')
 const dialog = page.getByRole('dialog', { name: 'Confirm request action' })
 await interaction.check(dialog.getByRole('checkbox'), 'trade-step-286')
 const lost = page.waitForResponse(response => response.url().endsWith('/accept') && response.request().method() === 'POST')
 await interaction.click(dialog.getByRole('button', { name: 'Accept proposal', exact: true }), 'trade-step-288')
 const lostResponse = await lost; assert.equal(lostResponse.status(), 503); await lostResponse.finished()
 await page.getByRole('heading', { name: 'The action result needs confirmation.', exact: true }).waitFor()
 const committed = await data(await buyer.request.get(api + '/orders/' + id))
 assert.equal(committed.status, 'ready_for_review')
 assert.equal(observed.filter(entry => entry.method === 'POST' && entry.path.endsWith('/accept')).length, 1)
 const slot = 'leshine.portal.action:' + seed.buyerAccountPublicId
 const raw = await page.evaluate(slot => sessionStorage.getItem(slot), slot)
 const marker = JSON.parse(raw)
 assert.equal(marker.request_id, id); assert.equal(marker.action, 'accept_proposal')
 assert.equal(marker.revision_id, proposed.original_receipt.revision_id)
 assert.equal(marker.proposal_hash, proposed.original_receipt.content_hash)
 assert.ok(!raw.includes('PO-OWNED-BROWSER') && !raw.includes(delivery.address_line1) && !raw.includes(seed.buyerEmail))
 await page.reload()
 await page.getByRole('heading', { name: 'The action result needs confirmation.', exact: true }).waitFor()
 assert.equal(await page.getByRole('button', { name: 'Retry original action', exact: true }).count(), 0)
 await geometry('actual-main-refresh-recovery')
 const recovered = page.waitForResponse(response => response.url().includes('/action-receipt?') && response.request().method() === 'GET')
 await interaction.click(page.getByRole('button', { name: 'Check original action receipt', exact: true }), 'trade-step-306')
 const recovery = await data(await recovered)
 assert.equal(recovery.found, true); assert.equal(recovery.command.payload_hash, marker.payload_hash)
 assert.equal(recovery.receipt.original_receipt.revision_id, marker.revision_id)
 assert.equal(recovery.receipt.original_receipt.row_version, committed.row_version)
 await page.getByText(/Original action on .* was recorded/).waitFor()
 assert.equal(await page.evaluate(slot => sessionStorage.getItem(slot), slot), null)
 assert.equal(observed.filter(entry => entry.method === 'POST' && entry.path.endsWith('/accept')).length, 1)
 scenarios.push('real committed acceptance ACK fault and refresh GET-only exact receipt')
 const acceptedVersion = committed.row_version
 await interaction.click(staffPage.getByRole('button', { name: '处理请求', exact: true }), 'trade-step-316')
 await staffReview.getByText('当前版本完整条款', { exact: true }).waitFor()
 await interaction.click(staffReview.locator('.el-radio-button').filter({ hasText: '审核并生成正式 PI' }), 'trade-step-318')
 await employeeGeometry(staffPage, staffReview, 'actual-main-employee-approval')
 await interaction.click(staffReview.locator('.el-checkbox').filter({ hasText: '我已核对内容，确认审核并生成正式 PI' }), 'trade-step-320')
 assert.equal(await staffReview.getByRole('checkbox').isChecked(), true)
 const approvedResponse = staffPage.waitForResponse(response => response.url().endsWith('/orders/' + id + '/approve') && response.request().method() === 'POST')
 await interaction.click(staffReview.getByRole('button', { name: '确认操作', exact: true }), 'trade-step-323')
 const approved = await data(await approvedResponse)
 assert.equal(approved.current_state, 'invoice_created')
 await staffReview.waitFor({ state: 'hidden' })
 await staffPage.getByRole('button', { name: '处理原 PI', exact: true }).waitFor()
 await interaction.click(staffPage.getByRole('button', { name: '查看操作审计', exact: true }), 'trade-step-328')
 const audit = staffPage.getByRole('dialog', { name: '订单操作审计', exact: true })
 await audit.getByText('生成 PI', { exact: true }).waitFor()
 await audit.getByText('提交请求', { exact: true }).waitFor()
 await employeeGeometry(staffPage, audit, 'actual-main-employee-audit')
 await interaction.click(audit.getByRole('button', { name: '关闭此对话框', exact: true }), 'trade-step-333')
 await audit.waitFor({ state: 'hidden' })
 scenarios.push('actual Chinese employee UI approves the accepted version and reads the audit')
 const repeated = await data(await owner.context.post(admin + '/orders/' + id + '/approve', { headers: { ...owner.headers, 'If-Match': '"' + acceptedVersion + '"' }, data: approval }))
 assert.equal(repeated.replayed, true); assert.deepEqual(repeated.original_receipt, approved.original_receipt)
 await interaction.click(page.getByRole('button', { name: 'Refresh details', exact: true }), 'trade-step-338')
 await page.getByRole('button', { name: 'Download confirmed PI', exact: true }).waitFor()
 const confirmedNotice = page.locator('.session-notice').filter({ hasText: 'Original action on' })
 assert.match(await confirmedNotice.innerText(), /Request status when checked: Awaiting final approval/)
 assert.ok(!(await confirmedNotice.innerText()).includes('Current request status:'))
 assert.ok(!(await confirmedNotice.innerText()).includes('The details below are refreshed from the server.'))
 assert.equal(await page.locator('.order-summary-bar .order-badge').innerText(), 'PI created')
 const downloaded = page.waitForEvent('download')
 await interaction.click(page.getByRole('button', { name: 'Download confirmed PI', exact: true }), 'trade-step-346')
 const pdf = await downloaded; assert.equal(await pdf.failure(), null); await pdf.saveAs(output + '/confirmed.pdf')
 const pdfBefore = await buyer.request.get(api + '/orders/' + id + '/pi')
 assert.equal(pdfBefore.status(), 200); const pdfBytes = await pdfBefore.body(); assert.equal(pdfBytes.subarray(0, 5).toString(), '%PDF-')
 scenarios.push('employee unique PI replay and actual customer PDF download')
 entries[0].display_value = 'Buyer New Straight'; entries[0].customer_sku = 'BUYER-NEW-20'
 mapping = await openMapping(mappingEditor.page)
 const changedSku = mapping.locator('.mapping-entry').filter({ hasText: '单规格型号名 / 客户货号' })
 await interaction.fill(changedSku.getByRole('textbox', { name: /^客户展示名 / }), 'Buyer New Straight', 'trade-step-354')
 await interaction.fill(changedSku.getByRole('textbox', { name: /^客户货号 / }), 'BUYER-NEW-20', 'trade-step-355')
 const updated = await publishMapping(mappingEditor.page, mapping, 1, 'Buyer New Straight', 'Buyer Natural Black', 'BUYER-NEW-20', 'actual-main-mapping-update')
 const scopedCustomersResponse = outsider.page.waitForResponse(response => response.url().split('?')[0] === admin + '/customers' && response.request().method() === 'GET')
 await outsider.page.goto(origin + '/portal/customers')
 const scopedCustomers = await data(await scopedCustomersResponse)
 assert.ok(scopedCustomers.items.some(item => item.id === seed.otherAccessId))
 assert.ok(!scopedCustomers.items.some(item => item.id === seed.accessId))
 await outsider.page.locator('button[data-portal-access="' + seed.otherAccessId + '"]').waitFor({ state: 'visible' })
 assert.equal(await outsider.page.locator('button[data-portal-access="' + seed.accessId + '"]').count(), 0)
 for (const operation of ['read', 'preview', 'publish']) {
  const path = admin + '/customers/' + seed.accessId + '/mapping' + (operation === 'read' ? '' : '/' + operation)
  const response = operation === 'read' ? await other.context.get(path, { headers: other.headers }) : await other.context.post(path, { headers: { ...other.headers, 'If-Match': '"' + updated.row_version + '"' }, data: { base_version: 2, entries } })
  assert.equal(response.status(), 404)
  assert.equal((await response.json()).data.error_code, 'RESOURCE_NOT_FOUND')
 }
 const retainedMapping = await data(await owner.context.get(admin + '/customers/' + seed.accessId + '/mapping', { headers: owner.headers }))
 assert.equal(retainedMapping.mapping_version, 2); assert.equal(retainedMapping.row_version, updated.row_version)
 assert.ok(retainedMapping.entries.some(entry => entry.kind === 'sku' && entry.source_key === seed.itemId && entry.display_value === 'Buyer New Straight' && entry.customer_sku === 'BUYER-NEW-20'))
 scenarios.push('actual Chinese mapping revision and foreign salesperson list/read/preview/publish isolation')
 const catalogue = await data(await buyer.request.get(api + '/catalog'))
 assert.ok(catalogue.items.some(item => item.item_id === seed.itemId && item.model_name === 'Buyer New Straight' && item.customer_sku === 'BUYER-NEW-20'))
 const history = await data(await buyer.request.get(api + '/orders/' + id))
 assert.equal(history.items[0].display_snapshot.model_name, 'Buyer Signature Straight')
 const pdfAfter = await buyer.request.get(api + '/orders/' + id + '/pi'); assert.equal(pdfAfter.status(), 200)
 // ReportLab includes per-render timestamps. The owning pytest verifies complete PDF
 // text and page counts plus every Publication/Invoice/Item/Conversion/Intent column.
 // Persist this actual response so those strict comparisons cover both sides of mapping.
 await writeFile(output + '/after-mapping.pdf', await pdfAfter.body())
 await interaction.click(page.getByRole('button', { name: 'Refresh details', exact: true }), 'trade-step-383')
 await page.getByRole('button', { name: 'Download confirmed PI', exact: true }).waitFor()
 await geometry('actual-main-confirmed-pi')
 scenarios.push('new mapping leaves historical request and published PDF unchanged')
 const foreign = await browser.newContext({ viewport: { width: 390, height: 1000 } }); contexts.push(foreign)
 const foreignPage = await foreign.newPage(); watch(foreignPage)
 const foreignCatalogResponse = foreignPage.waitForResponse(response => response.url().split('?')[0] === api + '/catalog' && response.request().method() === 'GET')
 await signIn(foreign, foreignPage, seed.otherBuyerEmail)
 const foreignCatalog = await data(await foreignCatalogResponse)
 const ownItem = foreignCatalog.items.find(item => item.item_id === seed.itemId)
 assert.ok(ownItem); assert.equal(ownItem.model_name, seed.standardModel); assert.equal(ownItem.color_name, seed.standardColor)
 assert.ok(!foreignCatalog.items.some(item => ['Buyer New Straight', 'Buyer Signature Straight'].includes(item.model_name) || item.customer_sku === 'BUYER-NEW-20'))
 await foreignPage.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true }).waitFor({ state: 'visible' })
 assert.ok(!(await foreignPage.locator('body').innerText()).includes('Buyer New Straight'))
 assert.ok(!(await foreignPage.locator('body').innerText()).includes('Buyer Signature Straight'))
 assert.ok(!(await foreignPage.locator('body').innerText()).includes('BUYER-NEW-20'))
 for (const suffix of ['', '/pi', '/action-receipt?action=accept_proposal&payload_hash=' + marker.payload_hash + '&revision_id=' + marker.revision_id + '&proposal_hash=' + marker.proposal_hash]) {
  const denied = await foreign.request.get(api + '/orders/' + id + suffix)
  assert.equal(denied.status(), 404); assert.equal((await denied.json()).data.error_code, 'RESOURCE_NOT_FOUND')
 }
 await foreignPage.goto(origin + '/orders/' + id)
 await foreignPage.getByRole('alert').waitFor()
 assert.ok(!(await foreignPage.locator('body').innerText()).includes('Buyer Signature Straight'))
 scenarios.push('other real OTP customer cannot read request receipt or PI')
 // Approved members share this company's orders; disabling one account revokes only it.
 await invited.page.goto(origin + '/orders/' + id)
 await invited.page.getByRole('button', { name: 'Download confirmed PI', exact: true }).waitFor()
 assert.ok((await invited.page.locator('body').innerText()).includes('Buyer Signature Straight'))
 const me = await data(await invited.context.request.get(api + '/session'))
 assert.equal(me.me.account_public_id, invited.accountId)
 const manager = invited.administrator.page
 await manager.goto(origin + '/portal/customers')
 await interaction.click(manager.locator('button[data-portal-access="' + seed.accessId + '"]'), 'trade-step-415')
 await interaction.click(manager.locator('button[data-portal-action="account"][data-portal-account="' + invited.accountId + '"]'), 'trade-step-416')
 const disabledAccount = manager.locator('.portal-access-action:visible')
 await interaction.fill(disabledAccount.getByRole('textbox', { name: '操作原因', exact: true }), 'Owned browser disable invited colleague', 'trade-step-418')
 assert.equal(await disabledAccount.getByRole('button', { name: '确认操作', exact: true }).isDisabled(), true)
 await interaction.click(disabledAccount.locator('.el-checkbox').filter({ hasText: '我已核对客户与影响' }), 'trade-step-420')
 const savedAccount = manager.waitForResponse(response => response.url() === admin + '/accounts/' + invited.accountId && response.request().method() === 'PATCH')
 await interaction.click(disabledAccount.getByRole('button', { name: '确认操作', exact: true }), 'trade-step-422')
 const savedResponse = await savedAccount
 assert.equal(savedResponse.request().postDataJSON().status, 'disabled')
 assert.match(savedResponse.request().headers()['if-match'], /^"[1-9][0-9]*"$/)
 assert.equal((await data(savedResponse)).status, 'disabled')
 await disabledAccount.waitFor({ state: 'hidden' })
 assert.equal((await invited.context.request.get(api + '/orders/' + id)).status(), 401)
 await interaction.click(invited.page.getByRole('button', { name: 'Refresh details', exact: true }), 'trade-step-429')
 await invited.page.getByLabel('Email address', { exact: true }).waitFor()
 assert.equal(await invited.page.locator('.portal-shell').count(), 0)
 assert.ok(!(await invited.page.locator('body').innerText()).includes('Buyer Signature Straight'))
 assert.equal((await buyer.request.get(api + '/orders/' + id)).status(), 200)
 scenarios.push('same-company activated member can read history; Chinese account disable revokes only that member')
 const limited = await data(await root.context.patch(admin + '/customers/' + seed.accessId, { headers: { ...root.headers, 'If-Match': '"' + updated.row_version + '"' }, data: { status: 'enabled', capabilities: { can_order: false, can_view_price: false }, reason: 'Owned browser revoke customer capabilities' } }))
 assert.ok(limited.row_version > updated.row_version)
 const revokedReceipt = await buyer.request.get(api + '/orders/' + id + '/action-receipt', { params: { action: marker.action, payload_hash: marker.payload_hash, revision_id: marker.revision_id, proposal_hash: marker.proposal_hash } })
 assert.equal(revokedReceipt.status(), 401)
 await interaction.click(page.getByRole('button', { name: 'Refresh details', exact: true }), 'trade-step-439')
 await page.getByLabel('Email address', { exact: true }).waitFor()
 assert.equal(await page.locator('.portal-shell').count(), 0)
 assert.ok(!(await page.locator('body').innerText()).includes('Buyer Signature Straight'))
 const disabled = await root.context.put(origin + '/api/auth/users/' + seed.ownerId, { headers: root.headers, data: { is_active: false } })
 assert.equal(disabled.status(), 200)
 assert.equal((await owner.context.get(admin + '/orders/' + id, { headers: owner.headers })).status(), 403)
 assert.equal((await owner.context.post(admin + '/orders/' + id + '/approve', { headers: { ...owner.headers, 'If-Match': '"' + acceptedVersion + '"' }, data: approval })).status(), 403)
 await interaction.click(staffPage.locator('.detail-drawer .el-drawer__close-btn'), 'trade-step-447')
 await interaction.click(staffPage.getByRole('button', { name: '刷新', exact: true }), 'trade-step-448')
 await staffPage.getByText('当前账号没有查看权限。', { exact: true }).waitFor()
 assert.equal(await staffPage.getByRole('button', { name: '详情', exact: true }).count(), 0)
 scenarios.push('current revocation denies old employee JWT and clears the actual Chinese UI list')
 scenarios.push('current customer revocation clears browser and current employee revocation denies old JWT')
 assert.deepEqual(errors, [])
 const report = { status: 'pass', scope: 'Actual built English customer and Chinese employee UIs, app.main, OTP/JWT and owned MySQL; synthetic upstream; controlled single ACK fault; loopback HTTP proxy harness, not production TLS/Nginx', apiInterceptions: 0, requestId: id, portalPostAccept: observed.filter(entry => entry.method === 'POST' && entry.path.endsWith('/accept')).length,
  receiptGets: observed.filter(entry => entry.method === 'GET' && entry.path.endsWith('/action-receipt')).length, rejectedActivationChallengeId: invited.rejectedChallengeId, widths: [1440, 390, 320], interaction: interaction.summary(), scenarios }
 await writeFile(output + '/report.json', JSON.stringify(report, null, 2))
 console.log(JSON.stringify(report))
} finally {
 for (const context of employees) await context.dispose()
 for (const context of contexts) await context.close()
 await browser.close()
}
