import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const [origin, modulePath, executablePath, output] = process.argv.slice(2)
assert.match(origin, /^http:\/\/127\.0\.0\.1:\d+$/)
let privateInput = ''
for await (const chunk of process.stdin) privateInput += chunk.toString('utf8')
const seed = JSON.parse(privateInput); privateInput = ''
const { chromium, request } = createRequire(import.meta.url)(modulePath)
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ executablePath, headless: true })
const contexts = [], requests = [], scenarios = [], errors = []
const api = origin + '/api/portal/v1', admin = origin + '/api/portal/admin/v1'
function watch(page) {
 page.on('pageerror', error => errors.push(error.name))
 page.on('request', event => { const path = new URL(event.url()).pathname; if (path.startsWith('/api/')) requests.push({ path, method: event.method() }) })
}
async function data(response, expected = 200) {
 assert.equal(response.status(), expected, 'Unexpected response: ' + new URL(response.url()).pathname)
 const body = await response.json(); assert.equal(body.code, expected); return body.data
}
async function employee(username) {
 const context = await request.newContext({ baseURL: origin }); contexts.push(context)
 const response = await context.post('/api/auth/login', { data: { username, password: seed.password } })
 assert.equal(response.status(), 200)
 const result = await response.json(); return { context, headers: { Authorization: 'Bearer ' + result.access_token } }
}
async function geometry(page, dialog, label) {
 for (const width of [1440, 390, 320]) {
  await page.setViewportSize({ width, height: 1000 })
  await dialog.locator('.el-dialog__footer').scrollIntoViewIfNeeded()
  assert.equal(await dialog.evaluate(element => element.scrollWidth > element.clientWidth + 1), false)
  await dialog.screenshot({ path: output + '/' + label + '-' + width + '.png', animations: 'disabled' })
 }
 await page.setViewportSize({ width: 320, height: 1000 })
}
async function confirm(dialog, label) {
 await dialog.locator('.el-checkbox').filter({ hasText: label }).click()
}
try {
 const owner = await employee(seed.ownerUsername), other = await employee(seed.otherUsername)
 const rootContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } }); contexts.push(rootContext)
 const page = await rootContext.newPage(); watch(page)
 await page.goto(origin + '/portal/customers')
 await page.getByLabel('用户名', { exact: true }).fill(seed.rootUsername)
 await page.getByLabel('密码', { exact: true }).fill(seed.password)
 const loggedIn = page.waitForResponse(response => response.url().endsWith('/api/auth/login') && response.request().method() === 'POST')
 await page.locator('button[type="submit"]').click(); assert.equal((await loggedIn).status(), 200)
 await page.locator('.portal-heading').getByRole('heading', { name: '客户访问与采购账号', exact: true }).waitFor()
 const candidatesResponse = page.waitForResponse(response => response.url().split('?')[0] === admin + '/onboarding/customers' && response.request().method() === 'GET')
 await page.getByRole('button', { name: '开通客户门户', exact: true }).click()
 const candidates = await data(await candidatesResponse)
 const candidate = candidates.items.find(item => item.canonical_customer_id === seed.onboardCustomerId)
 const blocked = candidates.items.find(item => item.canonical_customer_id === seed.blockedCustomerId)
 assert.ok(candidate?.ready && candidate.existing_access === null)
 assert.equal(candidate.assignment_id, seed.onboardAssignmentId); assert.equal(candidate.okki_identity_id, seed.onboardIdentityId)
 assert.ok(blocked && !blocked.ready && blocked.blocked_reasons.includes('VERIFIED_IDENTITY_MISSING'))
 const onboarding = page.locator('.portal-onboarding-dialog:visible')
 assert.equal(await onboarding.getByRole('row').filter({ hasText: seed.blockedCustomerCode }).getByRole('button', { name: '选择此客户', exact: true }).isDisabled(), true)
 const optionsResponse = page.waitForResponse(response => response.url().split('?')[0] === admin + '/onboarding/catalog' && response.request().method() === 'GET')
 await onboarding.getByRole('row').filter({ hasText: seed.onboardCustomerCode }).getByRole('button', { name: '选择此客户', exact: true }).click()
 const options = await data(await optionsResponse)
 assert.ok(options.items.some(item => item.id === seed.itemId && item.model_name === seed.standardModel && item.color_name === seed.standardColor))
 const grantName = '授权 ' + seed.standardModel + ' ' + seed.standardColor + ' ' + seed.itemId
 const grant = onboarding.getByRole('checkbox', { name: grantName, exact: true, includeHidden: true })
 await grant.locator('..').click(); assert.equal(await grant.isChecked(), true)
 assert.equal(await onboarding.getByRole('button', { name: '创建授权草稿', exact: true }).isDisabled(), true)
 await geometry(page, onboarding, 'actual-main-onboarding-draft')
 await confirm(onboarding, '我已核对公司身份')
 const creation = page.waitForResponse(response => response.url() === admin + '/customers' && response.request().method() === 'POST')
 await onboarding.getByRole('button', { name: '创建授权草稿', exact: true }).click()
 const createResponse = await creation
 const body = createResponse.request().postDataJSON()
 assert.equal(body.canonical_customer_id, seed.onboardCustomerId); assert.equal(body.assignment_id, seed.onboardAssignmentId)
 assert.equal(body.okki_identity_id, seed.onboardIdentityId); assert.equal(body.binding_fingerprint, candidate.binding_fingerprint)
 assert.deepEqual(body.catalog_item_ids, [seed.itemId]); assert.deepEqual(body.capabilities, { can_view_price: true, can_order: true })
 const created = await data(createResponse, 201), accessId = created.id
 assert.equal(created.status, 'draft'); assert.equal(created.canonical_customer_id, seed.onboardCustomerId)
 await onboarding.waitFor({ state: 'hidden' })
 await page.getByRole('button', { name: '设置客户访问', exact: true }).click()
 const enable = page.locator('.portal-access-action:visible')
 await enable.locator('.el-radio-button').filter({ hasText: '启用' }).click()
 await enable.getByRole('textbox', { name: '操作原因', exact: true }).fill('Owned browser enable new scoped customer')
 assert.equal(await enable.getByRole('button', { name: '确认操作', exact: true }).isDisabled(), true)
 await confirm(enable, '我已核对客户与影响')
 const enabledResponse = page.waitForResponse(response => response.url() === admin + '/customers/' + accessId && response.request().method() === 'PATCH')
 await enable.getByRole('button', { name: '确认操作', exact: true }).click()
 const enableResponse = await enabledResponse
 assert.equal(enableResponse.request().headers()['if-match'], '"' + created.row_version + '"')
 const enabled = await data(enableResponse); assert.equal(enabled.status, 'enabled')
 await enable.waitFor({ state: 'hidden' })
 scenarios.push('actual Ark choices reject missing identity and create one bound draft then explicitly enable')
 // Scoped write permission does not allow a different salesperson to take this customer.
 const ownerList = await data(await owner.context.get(admin + '/customers', { headers: owner.headers }))
 const otherList = await data(await other.context.get(admin + '/customers', { headers: other.headers }))
 assert.ok(ownerList.items.some(item => item.id === accessId))
 assert.ok(otherList.items.some(item => item.id === seed.otherAccessId)); assert.ok(!otherList.items.some(item => item.id === accessId))
 assert.equal((await other.context.get(admin + '/customers/' + accessId + '/catalog', { headers: other.headers })).status(), 404)
 const denied = await other.context.patch(admin + '/customers/' + accessId + '/catalog', { headers: { ...other.headers, 'If-Match': '"' + enabled.row_version + '"' }, data: { catalog_item_ids: [], reason: 'Cross salesperson must be rejected' } })
 assert.equal(denied.status(), 404); assert.equal((await denied.json()).data.error_code, 'RESOURCE_NOT_FOUND')
 scenarios.push('current scoped catalog admin cannot read or write another salesperson customer')
 await page.getByRole('button', { name: '邀请采购账号', exact: true }).click()
 const invite = page.locator('.portal-access-action:visible')
 await invite.getByRole('textbox', { name: '采购邮箱', exact: true }).fill(seed.onboardEmail)
 await invite.getByRole('textbox', { name: '采购联系人', exact: true }).fill('New scoped buyer')
 await confirm(invite, '我已核对客户与影响')
 const inviteResponse = page.waitForResponse(response => response.url() === admin + '/customers/' + accessId + '/invitations' && response.request().method() === 'POST')
 await invite.getByRole('button', { name: '确认操作', exact: true }).click()
 const invited = await data(await inviteResponse, 201); await invite.waitFor({ state: 'hidden' })
 const buyer = await browser.newContext({ viewport: { width: 390, height: 1000 } }); contexts.push(buyer)
 const customerPage = await buyer.newPage(); watch(customerPage)
 async function mailbox() {
  const response = await buyer.request.get(origin + '/__owned/invitation/' + invited.invitation_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
  assert.equal(response.status(), 200); return response.json()
 }
 const mailboxEvidence = await mailbox()
 const beforeLanding = requests.length
 await customerPage.goto(origin + '/activate#token=' + encodeURIComponent(mailboxEvidence.token))
 await customerPage.getByText('YOUR INVITATION', { exact: true }).waitFor(); await customerPage.waitForLoadState('networkidle')
 assert.equal(customerPage.url(), origin + '/activate'); assert.equal(requests.length, beforeLanding)
 assert.equal((await mailbox()).accountPublicId, mailboxEvidence.accountPublicId)
 await customerPage.getByLabel('Email address', { exact: true }).fill(seed.onboardEmail)
 const challengeResponse = customerPage.waitForResponse(response => response.url() === api + '/auth/challenges' && response.request().method() === 'POST')
 await customerPage.getByRole('button', { name: /Continue with email/ }).click()
 const challenge = await data(await challengeResponse, 202)
 const activationRequestedAt = Date.now()
 const codeResponse = await buyer.request.get(origin + '/__owned/otp/' + challenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
 assert.equal(codeResponse.status(), 200); const { code } = await codeResponse.json(); assert.match(code, /^[0-9]{6}$/)
 await customerPage.getByLabel('Verification code', { exact: true }).fill(code)
 const verified = customerPage.waitForResponse(response => response.url() === api + '/auth/verify' && response.request().method() === 'POST')
 const catalogResponse = customerPage.waitForResponse(response => response.url().split('?')[0] === api + '/catalog' && response.request().method() === 'GET')
 await customerPage.getByRole('button', { name: /Activate your access/ }).click(); await data(await verified)
 const catalogue = await data(await catalogResponse)
 assert.equal(catalogue.items.length, 1); assert.equal(catalogue.items[0].item_id, seed.itemId)
 await customerPage.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true }).waitFor()
 const session = await data(await buyer.request.get(api + '/session'))
 assert.equal(session.me.account_public_id, mailboxEvidence.accountPublicId)
 const retired = await browser.newContext({ storageState: { cookies: await buyer.cookies(), origins: [] } }); contexts.push(retired)
 const quote = await data(await buyer.request.post(api + '/quotes', { headers: { Origin: origin, 'X-Portal-CSRF': session.csrf_token }, data: { items: [{ item_id: seed.itemId, quantity: 1 }], delivery: { contact_name: 'New buyer', phone: '+44 10000000', address_line1: '20 Example Street', city: 'London', country_code: 'GB' } } }), 201)
 assert.equal(quote.status, 'valid')
 scenarios.push('new UI-created access grants exactly one standard SKU after actual invitation OTP activation')
 async function saveCatalog(selected, version, label) {
  await page.getByRole('button', { name: '管理商品授权', exact: true }).click()
  const dialog = page.locator('.portal-catalog-access:visible')
  const checkbox = dialog.getByRole('checkbox', { name: grantName, exact: true, includeHidden: true })
  await checkbox.waitFor({ state: 'attached' })
  if (await checkbox.isChecked() !== selected) await checkbox.locator('..').click()
  assert.equal(await checkbox.isChecked(), selected)
  await dialog.getByRole('textbox', { name: '商品授权操作原因', exact: true }).fill(selected ? 'Owned browser restore selected SKU' : 'Owned browser remove all selected SKUs')
  assert.equal(await dialog.getByRole('button', { name: '保存商品授权', exact: true }).isDisabled(), true)
  await geometry(page, dialog, label)
  await confirm(dialog, '我已核对新增、移除和保留商品')
  const saving = page.waitForResponse(response => response.url() === admin + '/customers/' + accessId + '/catalog' && response.request().method() === 'PATCH')
  await dialog.getByRole('button', { name: '保存商品授权', exact: true }).click()
  const response = await saving
  assert.equal(response.request().headers()['if-match'], '"' + version + '"')
  assert.deepEqual(response.request().postDataJSON().catalog_item_ids, selected ? [seed.itemId] : [])
  const result = await data(response); await dialog.waitFor({ state: 'hidden' }); return result
 }
 const removed = await saveCatalog(false, enabled.row_version, 'actual-main-catalog-remove')
 assert.deepEqual(removed.items, []); assert.equal(removed.status, 'enabled')
 assert.deepEqual(removed.capabilities, enabled.capabilities)
 assert.equal((await buyer.request.get(api + '/catalog')).status(), 401)
 await customerPage.goto(origin + '/collection')
 await customerPage.getByLabel('Email address', { exact: true }).waitFor()
 assert.equal(await customerPage.locator('.portal-shell').count(), 0)
 assert.ok(!(await customerPage.locator('body').innerText()).includes(seed.standardModel))
 scenarios.push('actual catalog removal invalidates only new customer session and its previous quote')
 const restored = await saveCatalog(true, removed.row_version, 'actual-main-catalog-restore')
 assert.equal(restored.items.length, 1); assert.equal(restored.items[0].id, seed.itemId)
 assert.equal(restored.status, 'enabled'); assert.deepEqual(restored.capabilities, enabled.capabilities)
 assert.equal(restored.catalog_version, created.catalog_version + 2)
 assert.equal((await buyer.request.get(api + '/session')).status(), 401)
 scenarios.push('actual catalog restore preserves explicit capabilities and does not revive revoked sessions')
 // Respect the real per-email 60-second cooldown; no test clock, rate override or DB edits.
 await new Promise(resolve => setTimeout(resolve, Math.max(0, activationRequestedAt + 61000 - Date.now())))
 await customerPage.setViewportSize({ width: 320, height: 1000 })
 await customerPage.getByLabel('Email address', { exact: true }).fill(seed.onboardEmail)
 const loginChallengeResponse = customerPage.waitForResponse(response => response.url() === api + '/auth/challenges' && response.request().method() === 'POST')
 await customerPage.getByRole('button', { name: /Continue with email/ }).click()
 const loginChallenge = await data(await loginChallengeResponse, 202)
 assert.equal((await loginChallengeResponse).request().postDataJSON().purpose, 'login')
 assert.equal((await loginChallengeResponse).request().postDataJSON().invitation_token, undefined)
 const loginCodeResponse = await buyer.request.get(origin + '/__owned/otp/' + loginChallenge.challenge_id, { headers: { 'X-Owned-Broker': seed.brokerKey } })
 assert.equal(loginCodeResponse.status(), 200)
 const loginCode = (await loginCodeResponse.json()).code; assert.match(loginCode, /^[0-9]{6}$/)
 await customerPage.getByLabel('Verification code', { exact: true }).fill(loginCode)
 const loginVerified = customerPage.waitForResponse(response => response.url() === api + '/auth/verify' && response.request().method() === 'POST')
 const restoredCatalogResponse = customerPage.waitForResponse(response => response.url().split('?')[0] === api + '/catalog' && response.request().method() === 'GET')
 await customerPage.getByRole('button', { name: /Enter your collection/ }).click(); await data(await loginVerified)
 const restoredCatalog = await data(await restoredCatalogResponse)
 assert.equal(restoredCatalog.items.length, 1); assert.equal(restoredCatalog.items[0].item_id, seed.itemId)
 const productButton = customerPage.getByRole('button', { name: 'View ' + seed.standardModel + ', ' + seed.standardColor, exact: true })
 await productButton.waitFor()
 assert.equal(await customerPage.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1), false)
 await customerPage.screenshot({ path: output + '/actual-customer-restored-catalog-320.png', animations: 'disabled' })
 const renewed = await data(await buyer.request.get(api + '/session'))
 assert.equal(renewed.me.account_public_id, mailboxEvidence.accountPublicId)
 assert.notEqual(renewed.csrf_token, session.csrf_token)
 assert.equal((await retired.request.get(api + '/session')).status(), 401)
 assert.equal((await retired.request.get(api + '/catalog')).status(), 401)
 scenarios.push('actual 320px English OTP login reads restored current catalog while original session remains revoked')
 const restoredQuote = await data(await buyer.request.post(api + '/quotes', { headers: { Origin: origin, 'X-Portal-CSRF': renewed.csrf_token }, data: { items: [{ item_id: seed.itemId, quantity: 1 }], delivery: { contact_name: 'New buyer', phone: '+44 10000000', address_line1: '20 Example Street', city: 'London', country_code: 'GB' } } }), 201)
 assert.equal(restoredQuote.status, 'valid'); assert.notEqual(restoredQuote.quote_id, quote.quote_id)
 scenarios.push('new authorized session obtains a fresh quote without reviving the old quote')
 const catalogueAfterDenial = await data(await owner.context.get(admin + '/customers/' + accessId + '/catalog', { headers: owner.headers }))
 assert.equal(catalogueAfterDenial.row_version, restored.row_version)
 assert.equal(catalogueAfterDenial.items.length, 1); assert.equal(catalogueAfterDenial.items[0].id, seed.itemId)
 scenarios.push('current owner reads final granted catalogue; old customers and financial graph are checked by owning pytest')
 assert.deepEqual(errors, [])
 const report = { status: 'pass', scope: 'Actual new Ark access and catalog UI, customer OTP; owned MySQL and controlled upstream/mailbox; not SMTP/production', apiInterceptions: 0, accessId, quoteId: quote.quote_id,
  loginChallengeId: loginChallenge.challenge_id, restoredQuoteId: restoredQuote.quote_id, createdRowVersion: created.row_version, createdCatalogVersion: created.catalog_version, widths: [1440, 390, 320], scenarios }
 await writeFile(output + '/report.json', JSON.stringify(report, null, 2))
 console.log(JSON.stringify({ status: 'pass', scenarioGroups: scenarios.length, apiInterceptions: 0 }))
} finally { await Promise.all(contexts.map(context => context.dispose ? context.dispose() : context.close())); await browser.close() }
