export function createCustomerHubApi(client) {
  return {
    listWorkbench: params => client.get('/workbench', { params, showLoading: false }),
    listQualificationQueue: params => client.get('/qualification-queue', { params, showLoading: false }),
    getQualificationContext: taskId => client.get(`/qualification-queue/${taskId}`, { showLoading: false }),
    submitQualificationDecision: (taskId, payload) => client.post(`/qualification-queue/${taskId}/decision`, payload),
    listCustomerEvidence: (customerId, params) => client.get(`/customers/${customerId}/evidence`, { params, showLoading: false }),
    listCustomers: params => client.get('/customers', { params, showLoading: false }),
    getCustomer: customerId => client.get(`/customers/${customerId}`),
    listCustomerTimeline: (customerId, params) => client.get(`/customers/${customerId}/timeline`, { params, showLoading: false }),
    getAcquisitionProfile: () => client.get('/acquisition-profile'),
    saveAcquisitionProfile: payload => client.put('/acquisition-profile', payload),
    listSearchJobs: params => client.get('/search-jobs', { params, showLoading: false }),
    createSearchJob: payload => client.post('/search-jobs', payload),
    requeueSearchJob: jobId => client.post(`/search-jobs/${jobId}/requeue`),
    listSearchJobResults: (jobId, params) => client.get(`/search-jobs/${jobId}/results`, { params, showLoading: false }),
    createPublicPoolBatch: payload => client.post('/public-pool/batches', payload),
    getPublicPoolRules: () => client.get('/public-pool/rules'),
    savePublicPoolRules: payload => client.put('/public-pool/rules', payload),
    previewPublicPoolRules: payload => client.post('/public-pool/rules/preview', payload),
    createConfiguredPublicPoolBatch: payload => client.post('/public-pool/rules/batches', payload),
    listResearchTasks: params => client.get('/research-tasks', { params, showLoading: false }),
    getResearchTask: taskId => client.get(`/research-tasks/${taskId}`),
    reviewResearchTask: (taskId, reviewStatus) => client.post(`/research-tasks/${taskId}/result-review`, { review_status: reviewStatus }),
    listOpportunities: params => client.get('/opportunities', { params, showLoading: false }),
    updateOpportunity: (opportunityId, payload) => client.put(`/opportunities/${opportunityId}`, payload),
    listActions: params => client.get('/actions', { params, showLoading: false }),
    updateAction: (actionId, payload) => client.put(`/actions/${actionId}`, payload),
  }
}
