<template>
  <template v-if="tab === 'overview'">
    <DecisionMetrics :data="data.summary" :changes="data.comparison?.changes" :cards="overviewCards" />
    <div class="decision-grid-main"><section class="decision-panel"><div class="section-heading"><div><h2>成交走势</h2><p>下单按订单日期，发货按有效报工日期，充值按入账日期</p></div><el-select v-model="trendMetric" aria-label="趋势指标"><el-option label="业务下单金额" value="business_order_amount" /><el-option label="发货出库金额" value="shipped_amount" /><el-option v-if="data.finance" label="客户充值金额" value="recharge_amount" /><el-option label="数量" value="quantity" /></el-select></div><DecisionChart title="成交走势" :rows="data.trend" :value="trendMetric" :columns="trendColumns" @select="trendDrill" /><p class="decision-note">{{ data.meta.comparison_period ? `对照：${data.meta.comparison_period.start_date} 至 ${data.meta.comparison_period.end_date}` : '当前未使用对照周期' }} · 成交额不等于回款额。</p></section>
      <section class="decision-panel insight-panel"><div class="section-heading"><div><h2>事实与下一步</h2><p>程序计算事实，规则提供可核验建议</p></div><span class="decision-badge">{{ data.insights.length }} 条</span></div><InsightCards :insights="data.insights.slice(0, 6)" :customers="data.customers" @customer="$emit('profile', 'customer', $event)" @evidence="$emit('evidence', $event)" @action="$emit('action', $event)" /><GlassButton variant="link" @click="$emit('tab', 'actions')">查看全部行动与简报</GlassButton></section>
    </div>
    <div class="decision-grid"><section class="decision-panel"><h2>产品需求结构</h2><DecisionChart title="产品类型需求" type="bar" :rows="data.dimensions.product_type || []" x="label" value="value" :columns="dimensionColumns" @select="row => dimensionDrill('product_type', row)" /></section><section class="decision-panel"><h2>金额变化拆解</h2><div v-if="data.amount_decomposition" class="fact-grid"><div><span>数量贡献</span><strong>{{ money(data.amount_decomposition.quantity_contribution) }}</strong></div><div><span>混合单价贡献</span><strong>{{ money(data.amount_decomposition.weighted_price_contribution) }}</strong></div></div><p v-else class="decision-note">选择对照周期后展示数量与混合单价贡献。</p><p class="decision-note">{{ data.amount_decomposition?.limitation || '混合单价受产品结构变化影响，不等于同规格提价或利润变化。' }}</p><h3>商业订单与零价订单</h3><DecisionTable :rows="[data.summary]" :columns="commercialColumns" :paginate="false" /></section></div>
  </template>
  <template v-else-if="tab === 'products'">
    <ProductOperations :data="data" @evidence="$emit('evidence', $event)" />
    <div class="decision-panel"><div class="section-heading"><div><h2>交叉需求矩阵</h2><p>选两个维度，按所选指标观察组合；订单与客户跨组去重，组间不可直接相加</p></div></div><div class="dimension-controls"><label>指标<el-select v-model="query.metric"><el-option v-for="(text, value) in METRIC_LABELS" :key="value" :label="text" :value="value" /></el-select></label><label v-for="index in [0, 1]" :key="index">维度 {{ index + 1 }}<el-select v-model="query.dimensions[index]"><el-option v-for="field in Object.keys(options.dimensions)" :key="field" :label="FIELD_LABELS[field]" :value="field" :disabled="query.dimensions[1 - index] === field" /></el-select></label><GlassButton variant="primary" @click="$emit('apply')">更新矩阵</GlassButton></div><DecisionChart :title="`${FIELD_LABELS[applied.dimensions[0]]} × ${FIELD_LABELS[applied.dimensions[1]] || '未选择'} · ${METRIC_LABELS[applied.metric]}`" type="heatmap" x="x" :rows="data.matrix" :columns="matrixColumns" @select="matrixDrill" /></div>
    <div class="decision-grid"><section class="decision-panel"><div class="section-heading"><h2>属性贡献</h2><el-select v-model="productDimension" aria-label="产品属性"><el-option v-for="field in productFields" :key="field" :label="FIELD_LABELS[field]" :value="field" /></el-select></div><DecisionChart :title="`${FIELD_LABELS[productDimension]}贡献`" type="bar" :rows="data.dimensions[productDimension] || []" x="label" value="value" :columns="dimensionColumns" @select="row => dimensionDrill(productDimension, row)" /></section><section class="decision-panel"><h2>价格与折扣结构</h2><DecisionTable :rows="data.price_structure.price_bands" :columns="priceBandColumns" /><div class="fact-grid"><div><span>有记录原价的折扣额</span><strong>{{ money(data.price_structure.recorded_discount_amount) }}</strong></div><div><span>有记录原价的折扣率</span><strong>{{ percent(data.price_structure.discount_rate) }}</strong></div><div><span>工费金额</span><strong>{{ money(data.price_structure.labor_fee_amount) }}</strong></div><div><span>原价未知明细</span><strong>{{ number(data.price_structure.unknown_standard_item_count) }}</strong></div></div><p class="decision-note">{{ data.price_structure.limitation }}</p></section></div>
<div v-if="data.quantity_structure" class="decision-grid"><section class="decision-panel"><h2>明细件数分箱</h2><p class="decision-note">按筛选命中的产品明细行件数分箱；金额仅统计命中行。</p><DecisionTable :rows="data.quantity_structure.item_bands" :columns="itemQuantityColumns" action="明细证据" @open="row => $emit('evidence', row.evidence_refs)" /></section><section class="decision-panel"><h2>相关整单总件数分箱</h2><p class="decision-note">整单全部件数用于分箱；筛选命中数量与整单数量分别保留。</p><DecisionTable :rows="data.quantity_structure.order_bands" :columns="orderQuantityColumns" action="整单证据" @open="row => $emit('evidence', row.evidence_refs)" /></section></div>    <section class="decision-panel"><div class="section-heading"><div><h2>完整产品组合</h2><p>保留产品类型、工艺、网色、尺寸、长度、密度、发型系列与颜色</p></div><GlassButton @click="$emit('rows', 'items', {}, '匹配产品明细')">全部匹配明细</GlassButton><GlassButton @click="$emit('rows', 'orders', {}, '相关整单明细')">相关整单</GlassButton></div><DecisionTable :rows="data.products" :columns="productColumns" action="证据" @open="row => $emit('evidence', row.evidence_refs)" /></section>
  </template>
  <template v-else-if="tab === 'finance' && data.finance">
    <div class="decision-notice"><strong>资金独立口径</strong><span>{{ applied.finance_related_customers ? '按本次命中产品的相关客户分析资金' : '沿用客户与时间范围，资金忽略产品筛选' }} · {{ applied.start_date }} 至 {{ applied.end_date }}</span><el-checkbox v-model="query.finance_related_customers" @change="$emit('apply')">明确按相关客户分析资金</el-checkbox></div>
    <DecisionMetrics :data="data.finance.summary" :cards="financeCards" />
    <div class="decision-grid-main"><section class="decision-panel"><h2>资金变动桥</h2><DecisionChart title="资金桥构成（符号表示余额方向）" type="bar" x="label" value="amount" :rows="bridgeRows" :columns="[{ key: 'label', label: '构成' }, { key: 'amount', label: '金额', format: 'money' }]" @select="() => $emit('rows', 'ledger', {}, '资金流水')" /><div class="fact-grid"><div><span>期初余额</span><strong>{{ money(data.finance.summary.opening_balance) }}</strong></div><div><span>期末余额</span><strong>{{ money(data.finance.summary.closing_balance) }}</strong></div><div><span>净余额（已知客户）</span><strong>{{ money(data.finance.summary.net_balance) }}</strong></div><div><span>余额未知客户</span><strong>{{ number(data.finance.summary.unknown_balance_customer_count) }}</strong></div></div><p class="decision-note">充值、扣款、退款与人工调整分别显示；链路异常客户不生成强资金建议。</p></section><section class="decision-panel"><h2>充值趋势</h2><DecisionChart title="已入账充值" :rows="data.finance.trend" value="recharge_amount" :columns="[{ key: 'date', label: '日期' }, { key: 'recharge_amount', label: '充值额', format: 'money' }, { key: 'recharge_count', label: '笔数', format: 'number' }]" @select="() => $emit('rows', 'ledger', {}, '充值流水')" /><div class="fact-grid"><div><span>待审核申请金额</span><strong>{{ money(data.finance.summary.pending_recharge_amount) }}</strong></div><div><span>待审核笔数</span><strong>{{ number(data.finance.summary.pending_recharge_count) }}</strong></div></div><GlassButton variant="link" @click="$emit('rows', 'requests', {}, '充值与调整申请')">查看申请证据</GlassButton><p class="decision-note">申请展示当前审核状态，不还原过去时点状态；待审核金额不计入充值。</p></section></div>
    <section class="decision-panel"><h2>客户资金画像</h2><DecisionTable :rows="financeCustomers" :columns="financeCustomerColumns" action="客户画像" id-key="customer_id" @open="row => $emit('profile', 'customer', row.customer_id)" /><p class="decision-note">可覆盖天数基于可靠账链、最近 90 天有效扣款与购买样本；赊销客户不适用，负余额代表欠款。</p></section>
    <div class="decision-grid"><section class="decision-panel"><h2>充值后购货等待</h2><DecisionTable :rows="data.finance.recharge_purchase_waiting || []" :columns="waitingColumns" action="流水证据" @open="row => $emit('evidence', row.evidence_refs || [{ type: 'ledger', id: row.ledger_id }])" /></section><section class="decision-panel"><h2>审核效率</h2><DecisionTable :rows="[data.finance.review_metrics]" :columns="reviewColumns" :paginate="false" /><p class="decision-note">按完成审核申请统计；无样本指标保持未知。</p><h3>待审核申请等待</h3><DecisionTable :rows="data.finance.review_metrics.pending" :columns="pendingWaitColumns" action="申请证据" @open="row => $emit('evidence', [{ type: 'requests', id: row.request_id }])" /><h3>充值客户月后续购买观察</h3><DecisionTable :rows="financeCohortRows" :columns="cohortColumns" /><h3>期内首次充值客户观察（客户级）</h3><DecisionTable :rows="data.finance.cohorts.period_customers.map(row => ({ ...row, month: '本期首次充值客户' }))" :columns="cohortColumns" /><p class="decision-note">客户月与期内客户分母分别展示。同日先后未知，排除充值后购买；未成熟样本不算作未购买。</p></section></div>
  </template>
  <template v-else-if="tab === 'customers'">
    <CustomerOperations :data="data" @evidence="$emit('evidence', $event)" @profile="(kind, id) => $emit('profile', kind, id)" />
    <div class="decision-notice">客户列表包含授权范围内当期零购买客户。复购周期使用完整商业购买日历史，档案累计额与系统累计额分开。</div>
    <section class="decision-panel"><div class="section-heading"><h2>客户经营组合</h2><el-input v-model="customerSearch" placeholder="搜索客户 / 地区" clearable class="panel-search" aria-label="搜索客户" /></div><DecisionTable :rows="customers" :columns="customerColumns" id-key="customer_id" selectable :selection="customerSelection" action="360°画像" @select="id => toggleSelection(customerSelection, id)" @open="row => $emit('profile', 'customer', row.customer_id)" /><p class="decision-note">选择最多 4 位客户可按同一范围横向对比。</p></section>
    <section v-if="customerSelection.length" class="decision-panel"><h2>客户对比</h2><DecisionTable :rows="data.customers.filter(row => customerSelection.includes(row.customer_id))" :columns="customerCompareColumns" :paginate="false" /></section>
    <section class="decision-panel"><h2>首购与留存观察</h2><DecisionTable :rows="buyingCohortRows" :columns="cohortColumns" /><p class="decision-note">{{ data.meta.coverage_start ? `完整覆盖起点 ${data.meta.coverage_start}` : '完整历史覆盖未确认；仅展示系统首次观察和后续购买，不称为真实新客留存。' }}</p></section>
  </template>
  <template v-else-if="tab === 'people'">
    <div class="decision-notice">按当前负责人统计客户组合。没有历史归属事件快照，无法还原真实历史业绩排名。</div>
    <div class="person-grid"><article v-for="person in data.salespeople" :key="person.user_id || 'unassigned'" class="decision-panel person-card"><header><span class="person-avatar">{{ person.name?.slice(0, 1) }}</span><div><h2>{{ person.name }}</h2><p class="decision-note">当前归属客户组合</p></div><input type="checkbox" :checked="peopleSelection.includes(person.user_id)" :disabled="!peopleSelection.includes(person.user_id) && peopleSelection.length >= 4" :aria-label="`对比 ${person.name}`" @change="toggleSelection(peopleSelection, person.user_id)"></header><div class="fact-grid"><div><span>相关订单额</span><strong>{{ money(person.amount) }}</strong></div><div><span>归属客户</span><strong>{{ number(person.portfolio_customer_count) }}</strong></div><div><span>当期购买客户</span><strong>{{ number(person.active_customer_count) }}</strong></div><div><span>订单数</span><strong>{{ number(person.order_count) }}</strong></div></div><GlassButton variant="link" :disabled="!person.user_id" @click="$emit('profile', 'salesperson', person.user_id)">查看客户与产品组合</GlassButton></article></div>
    <section v-if="peopleSelection.length" class="decision-panel"><h2>当前人员客户组合对比</h2><DecisionTable :rows="data.salespeople.filter(row => peopleSelection.includes(row.user_id))" :columns="peopleColumns" :paginate="false" /></section>
    <section class="decision-panel"><h2>人员经营口径</h2><p class="decision-note">客户类型、购买频率与当前组合结构会影响成交额；对比用于核实支持需求，不把当前归属下历史金额认定为历史个人业绩。人员画像含完整客户清单、产品贡献与同周期趋势。</p><div class="p1-gate"><span class="decision-badge">P1 · 尚未启用</span><strong>历史业绩归属与净利润</strong><p>需负责人变更事件、历史快照和可靠成本数据，当前页面不估算。</p></div></section>
  </template>
  <template v-else-if="tab === 'trends'">
    <div class="decision-notice">此处反映本公司内贸成交需求样本，不能外推为全行业市场趋势。小样本、未知映射与集中度会限制结论。</div>
    <section class="decision-panel"><div class="section-heading"><div><h2>需求贡献与变化</h2><p>按产品、地区或渠道看绝对规模与变化</p></div><el-select v-model="trendDimension" aria-label="趋势维度"><el-option v-for="field in Object.keys(options.dimensions)" :key="field" :label="FIELD_LABELS[field]" :value="field" /></el-select><el-radio-group v-model="trendMode"><el-radio-button value="value">绝对规模</el-radio-button><el-radio-button value="amount_delta">金额绝对变化</el-radio-button></el-radio-group></div><DecisionChart :title="`${FIELD_LABELS[trendDimension]}需求${trendMode === 'value' ? '贡献' : '变化'}`" type="bar" x="label" :value="trendMode" :rows="trendRows" :columns="dimensionColumns" @select="row => dimensionDrill(trendDimension, row)" /><div class="fact-grid"><div><span>Top 3 金额集中度</span><strong>{{ percent(concentration) }}</strong></div><div><span>未知 / 待映射金额占比</span><strong>{{ percent(unknownShare) }}</strong></div><div><span>当前客户样本</span><strong>{{ number(data.summary.customer_count) }}</strong></div></div><p class="decision-note">{{ data.summary.customer_count < 10 ? '客户样本少于 10；仅用于观察事实，暂不形成强趋势建议。' : '集中度高的结构容易受少数客户影响；变化需结合客户与整单证据核验。' }}</p></section>
    <section class="decision-panel"><h2>变化证据</h2><DecisionTable :rows="trendRows" :columns="dimensionColumns" action="下钻" @open="row => dimensionDrill(trendDimension, row)" /></section>
    <section class="decision-panel p1-gate"><span class="decision-badge">P1 · 尚未启用</span><h2>预测、行业外推与利润趋势</h2><p>当前只呈现观察到的订单事实；待历史覆盖、稳定产品映射及成本口径具备后再评估。</p></section>
  </template>
</template>
<script setup>
import { computed, ref, watch } from 'vue'
import { Money, Goods, UserFilled, Wallet, Tickets, TrendCharts } from '@element-plus/icons-vue'
import GlassButton from '@/components/GlassButton.vue'
import DecisionMetrics from './DecisionMetrics.vue'
import CustomerOperations from './CustomerOperations.vue'
import ProductOperations from './ProductOperations.vue'
import DecisionChart from './DecisionChart.vue'
import DecisionTable from './DecisionTable.vue'
import InsightCards from './InsightCards.vue'
import { FIELD_LABELS, METRIC_LABELS, money, number, percent } from '../state'
const props = defineProps({ tab: String, data: Object, query: Object, applied: Object, options: Object })
const emit = defineEmits(['rows', 'profile', 'evidence', 'action', 'apply', 'tab'])
const trendMetric = ref('business_order_amount'), productDimension = ref('craft'), trendDimension = ref('province'), trendMode = ref('value'), customerSearch = ref(''), customerSelection = ref([]), peopleSelection = ref([])
watch(() => props.data.meta.run_id, () => { customerSelection.value = []; peopleSelection.value = [] })
const productFields = ['product_type', 'craft', 'net_color', 'size', 'length', 'density', 'hair_style_series', 'color']
const overviewCards = computed(() => [{ key: 'business_order_amount', label: '业务下单金额', format: 'money', icon: Money, note: '正常业务单，按下单日期统计' }, { key: 'shipped_amount', label: '发货出库金额', format: 'money', icon: Goods, tone: 'success', note: '有效发货完成报工数量 × 成交单价' }, { key: 'recharge_amount', label: '客户充值金额', format: 'money', icon: Wallet, tone: 'info', note: !props.data.finance ? '需要资金阅读权限' : props.applied.finance_related_customers ? '按本次相关客户实际充值入账' : '客户范围实际充值，忽略产品筛选' }, { key: 'customer_count', label: '下单客户个数', icon: UserFilled, tone: 'violet', note: '统计周期内同一客户只计一次' }])
const financeCards = [{ key: 'recharge_amount', label: '已入账充值', format: 'money', icon: Wallet, note: '仅正向充值流水' }, { key: 'net_order_deduction', label: '订单净扣款', format: 'money', icon: Tickets, tone: 'info', note: '退款与调整独立核对' }, { key: 'positive_balance', label: '正余额合计', format: 'money', icon: Money, tone: 'success', note: '已知余额，异常需另核验' }, { key: 'debt', label: '欠款合计', format: 'money', icon: TrendCharts, tone: 'warning', note: '负余额绝对值' }]
const col = (key, text, format, extra = {}) => ({ key, label: text, format, ...extra })
const trendColumns = [col('date', '日期'), col('business_order_amount', '业务下单金额', 'money'), col('shipped_amount', '发货出库金额', 'money'), col('recharge_amount', '客户充值金额', 'money'), col('quantity', '下单件数', 'number'), col('customer_count', '下单客户个数', 'number')]
const dimensionColumns = [col('label', '属性'), col('amount', '匹配额', 'money'), col('quantity', '数量', 'number'), col('order_count', '订单数', 'number'), col('customer_count', '客户数', 'number'), col('share', '金额占比', 'percent'), col('previous_amount', '对照金额', 'money'), col('amount_change.rate', '金额变化率', 'percent')]
const matrixColumns = [col('x', '维度一'), col('y', '维度二'), col('amount', '匹配额', 'money'), col('quantity', '数量', 'number'), col('order_count', '订单数', 'number'), col('customer_count', '客户数', 'number')]
const productColumns = [...productFields.map(field => col(`attrs.${field}`, FIELD_LABELS[field])), col('amount', '匹配额', 'money'), col('quantity', '数量', 'number'), col('order_count', '订单数', 'number'), col('customer_count', '客户数', 'number')]
const priceBandColumns = [col('band', '成交单价带'), col('amount', '金额', 'money'), col('quantity', '数量', 'number'), col('item_count', '明细数', 'number')]
const itemQuantityColumns = [col('band', '每行件数'), col('item_count', '明细行数', 'number'), col('quantity', '匹配数量', 'number'), col('amount', '匹配明细金额', 'money')]
const orderQuantityColumns = [col('band', '整单总件数'), col('order_count', '相关订单数', 'number'), col('whole_quantity', '整单全部数量', 'number'), col('matched_quantity', '筛选命中数量', 'number'), col('related_order_amount', '相关整单金额', 'money')]
const commercialColumns = [col('commercial_order_count', '商业订单', 'number'), col('zero_order_count', '零金额订单', 'number'), col('aftersales_order_count', '售后订单', 'number'), col('quantity', '匹配数量', 'number')]
const customerColumns = [col('shop_name', '客户', null, { link: true }), col('province', '省份'), col('city', '城市'), col('store_type', '门店类型'), col('amount', '相关整单额', 'money'), col('matched_amount', '命中明细额', 'money'), col('order_count', '订单数', 'number'), col('history.recency_days', '距末次购买天数', 'number'), col('history.cycle_days', '复购周期天数', 'number'), col('history.cycle_status', '购买节奏')]
const customerCompareColumns = [...customerColumns, col('history.purchase_days', '历史购买日', 'number'), col('history.system_amount', '系统累计额', 'money'), col('history.archival_amount', '档案累计额', 'money'), col('history.rfm.status', 'RFM样本状态')]
const peopleColumns = [col('name', '负责人'), col('portfolio_customer_count', '归属客户', 'number'), col('active_customer_count', '当期购买客户', 'number'), col('amount', '当前组合整单额', 'money'), col('quantity', '数量', 'number'), col('order_count', '订单数', 'number')]
const financeCustomerColumns = [col('shop_name', '客户', null, { link: true }), col('opening_balance', '期初余额', 'money'), col('closing_balance', '期末余额', 'money'), col('recharge_amount', '充值额', 'money'), col('net_order_deduction', '净订单扣款', 'money'), col('debt', '欠款', 'money'), col('pending_recharge_amount', '待审核', 'money'), col('coverage_days', '余额覆盖天数', 'number'), col('coverage_status', '覆盖指标状态'), col('recharge_cycle_days', '充值周期天数', 'number'), col('reliable', '账链可靠', null, { get: row => row.reliable ? '可靠' : '异常待核验' })]
const waitingColumns = [col('customer_id', '客户ID'), col('ledger_id', '充值流水ID'), col('next_order_id', '后续订单ID'), col('first_purchase_wait_days', '等待天数', 'number'), col('status', '观察状态')]
const pendingWaitColumns = [col('request_id', '申请ID'), col('customer_id', '客户ID'), col('wait_seconds', '等待秒数', 'number')]
const reviewColumns = [col('reviewed_count', '完成审核', 'number'), col('median_review_seconds', '审核中位秒数', 'number'), col('p90_review_seconds', '审核P90秒数', 'number'), { key: 'pending', label: '待审核', format: 'number', get: row => row.pending?.length }]
const cohortColumns = [col('month', '首购/充值月份'), col('window_days', '观察天数', 'number'), col('mature_count', '成熟样本', 'number'), { key: 'purchase_count', label: '后续购买', format: 'number', get: row => row.purchase_count ?? row.second_purchase_count }, col('rate', '观察购买率', 'percent'), col('immature_count', '尚未成熟', 'number')]
const customers = computed(() => props.data.customers.filter(row => `${row.shop_name} ${row.province} ${row.city}`.includes(customerSearch.value.trim())))
const financeCustomers = computed(() => (props.data.finance?.customers || []).map(row => ({ ...row, shop_name: row.shop_name || props.data.customers.find(customer => customer.customer_id === row.customer_id)?.shop_name || `客户 ${row.customer_id}` })))
const bridgeRows = computed(() => Object.entries(props.data.finance?.summary.bridge_components || {}).map(([key, value]) => ({ label: { recharge: '充值', order_charge: '订单扣款', order_adjustment_positive: '正向订单调整', order_adjustment_negative: '负向订单调整', order_refund: '退款', init: '期初初始化', adjust: '人工调整', level_adjust: '等级调整' }[key] || key, amount: ['order_charge', 'order_adjustment_negative'].includes(key) ? -value : value })))
const trendRows = computed(() => (props.data.dimensions[trendDimension.value] || []).map(row => ({ ...row, amount_delta: row.amount_change?.absolute ?? null })))
const concentration = computed(() => { const rows = props.data.dimensions[trendDimension.value] || []; const sum = rows.reduce((total, row) => total + row.amount, 0); return sum > 0 ? [...rows].sort((a, b) => b.amount - a.amount).slice(0, 3).reduce((total, row) => total + row.amount, 0) / sum : null })
const unknownShare = computed(() => { const rows = props.data.dimensions[trendDimension.value] || [], sum = rows.reduce((total, row) => total + row.amount, 0); return sum > 0 ? rows.filter(row => /未知|待映射|未归类/.test(row.label)).reduce((total, row) => total + row.amount, 0) / sum : null })
function observations(groups) { return (groups || []).flatMap(group => (group.observations || []).map(row => ({ ...row, month: group.month }))) }
const buyingCohortRows = computed(() => Array.isArray(props.data.cohorts) ? props.data.cohorts.flatMap(group => (group.observations || []).map(row => ({ ...row, month: group.month }))) : observations(props.data.cohorts?.monthly))
const financeCohortRows = computed(() => observations(props.data.finance?.cohorts?.monthly))
function toggleSelection(list, id) { const index = list.indexOf(id); if (index >= 0) list.splice(index, 1); else if (list.length < 4) list.push(id) }
function dimensionDrill(field, row) { emit('rows', 'items', { dimension: field, value: row.key }, `${FIELD_LABELS[field]}：${row.label} · 匹配明细`) }
function matrixDrill(row) { emit('evidence', row.evidence_refs) }
function trendDrill(row) {
  const type = trendMetric.value === 'shipped_amount' ? 'reports' : trendMetric.value === 'recharge_amount' ? 'ledger' : 'orders'
  const records = (props.data.evidence[type] || []).filter(item => type === 'reports' ? item.process_name === '发货完成' && item.reported_at?.slice(0, 10) === row.date : type === 'ledger' ? item.transaction_type === 'recharge' && item.amount > 0 && item.created_at?.slice(0, 10) === row.date : item.order_date === row.date)
  emit('evidence', records.map(item => ({ type, id: item.id })))
}
</script>
