"""Customer ordering portal: isolated identities, snapshots and permanent PI lineage.

No customer/account/catalog records are seeded. Do not run on shared DB from a developer machine.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "176_customer_order_portal"
down_revision = "175_receipt_recovery"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ark_order_portal_accounts',
    sa.Column('email_normalized', sa.String(length=254), nullable=False, comment='统一规范化登录邮箱'),
    sa.Column('email_display', sa.String(length=254), nullable=False, comment='对外显示邮箱'),
    sa.Column('contact_name', sa.String(length=100), nullable=False, comment='客户联系人姓名'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('auth_version', sa.BigInteger(), nullable=False, comment='访问授权撤销版本'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='邮箱持有验证时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("status IN ('invited','active','disabled')", name='ck_op_account_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_audit_events',
    sa.Column('actor_type', sa.String(length=16), nullable=False, comment='客户、员工或系统操作者类型'),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='对应类型操作者ID'),
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户customer_access关联记录'),
    sa.Column('object_type', sa.String(length=32), nullable=False, comment='审计对象类别'),
    sa.Column('object_public_id', sa.String(length=36), nullable=False, comment='目标对象公开ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='受控操作类型'),
    sa.Column('before_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='变更前版本'),
    sa.Column('after_version', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='变更后版本'),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='操作理由，禁止存凭证与完整个人资料'),
    sa.Column('safe_diff_json', sa.JSON(), nullable=False, comment='脱敏审计差异'),
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='排障关联ID'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_auth_barriers',
    sa.Column('code', sa.String(length=32), nullable=False, comment='稳定标识码'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='授权或配置版本'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ark_order_portal_auth_challenges',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户accounts关联记录'),
    sa.Column('invitation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户invitations关联记录'),
    sa.Column('preauth_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户preauth_sessions关联记录'),
    sa.Column('purpose', sa.String(length=16), nullable=False, comment='登录或邀请激活用途'),
    sa.Column('email_key_hash', sa.String(length=64), nullable=False, comment='邮箱限频键的受密钥保护摘要'),
    sa.Column('code_hmac', sa.String(length=64), nullable=False, comment='验证码作用域绑定的HMAC摘要'),
    sa.Column('issued_version', sa.BigInteger(), nullable=False, comment='签发时账号授权版本'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='验证码失败次数，最多五次'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='单次凭证消费时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='服务端撤销时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("purpose IN ('login','activate')", name='ck_op_challenge_purpose'),
    sa.CheckConstraint('attempts >= 0 AND attempts <= 5', name='ck_op_challenge_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_catalog_grants',
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('catalog_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户catalog_items关联记录'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("status IN ('enabled','disabled')", name='ck_op_catalog_grant_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'catalog_item_id', name='uq_op_catalog_grant'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_catalog_items',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('product_kind', sa.String(length=16), nullable=False, comment='标准商品类别，发品或配件'),
    sa.Column('source_namespace', sa.String(length=128), nullable=False, comment='标准SKU数据源命名空间'),
    sa.Column('product_id', sa.String(length=64), nullable=False, comment='标准商品ID，按字符串存储'),
    sa.Column('sku_id', sa.String(length=64), nullable=False, comment='标准规格ID，按字符串存储'),
    sa.Column('standard_fingerprint', sa.String(length=64), nullable=False, comment='标准SKU元数据指纹'),
    sa.Column('standard_json', sa.JSON(), nullable=False, comment='不可被客户别名覆盖的标准属性'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='站点默认型号展示名'),
    sa.Column('color_name', sa.String(length=128), nullable=False, comment='站点默认颜色展示名'),
    sa.Column('image_asset_id', sa.String(length=64), nullable=True, comment='受管理图片资产引用'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('inventory_unit', sa.String(length=32), nullable=False, comment='库存标准单位'),
    sa.Column('sale_unit', sa.String(length=32), nullable=False, comment='销售标准单位'),
    sa.Column('conversion_factor', sa.Numeric(precision=14, scale=6), nullable=False, comment='每销售单位对应库存单位量'),
    sa.Column('min_qty', sa.BigInteger(), nullable=False, comment='最小购买数量'),
    sa.Column('step_qty', sa.BigInteger(), nullable=False, comment='购买数量步长'),
    sa.Column('safety_buffer', sa.Numeric(precision=14, scale=6), nullable=False, comment='库存标准单位下的安全余量'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("product_kind IN ('hair','accessory')", name='ck_op_catalog_kind'),
    sa.CheckConstraint("status IN ('draft','published','disabled')", name='ck_op_catalog_status'),
    sa.CheckConstraint('conversion_factor > 0 AND min_qty > 0 AND step_qty > 0 AND safety_buffer >= 0', name='ck_op_catalog_quantity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('site_id', 'source_namespace', 'product_id', 'sku_id', name='uq_op_catalog_sku')
    )
    op.create_table('ark_order_portal_command_receipts',
    sa.Column('action', sa.String(length=32), nullable=False, comment='受控操作类型'),
    sa.Column('object_public_id', sa.String(length=36), nullable=False, comment='目标对象公开ID'),
    sa.Column('command_key', sa.String(length=160), nullable=False, comment='成功命令稳定身份'),
    sa.Column('payload_hash', sa.String(length=64), nullable=False, comment='命令规范化载荷摘要'),
    sa.Column('result_reference_json', sa.JSON(), nullable=False, comment='成功结果引用，不保存完整敏感响应'),
    sa.Column('first_actor_type', sa.String(length=16), nullable=False, comment='首次成功操作者类型'),
    sa.Column('first_actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='首次成功操作者ID'),
    sa.Column('completed_at', sa.DateTime(), nullable=False, comment='命令成功完成时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'object_public_id', 'command_key', name='uq_op_command_receipt'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_conversions',
    sa.Column('request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户requests关联记录'),
    sa.Column('approved_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户revisions关联记录'),
    sa.Column('operation_key', sa.String(length=64), nullable=False, comment='永久建票操作键'),
    sa.Column('payload_hash', sa.String(length=64), nullable=False, comment='命令规范化载荷摘要'),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='唯一关联方舟发票，不允许破坏引用删除'),
    sa.Column('invoice_document_version', sa.BigInteger(), nullable=True, comment='对应发票portal_document_version'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('created_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("status IN ('pending','created','tombstoned')", name='ck_op_conversion_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('operation_key'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('request_id'),
    sa.UniqueConstraint('request_id', 'invoice_id', name='uq_op_conversion_binding')
    )
    op.create_table('ark_order_portal_customer_access',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='方舟内部稳定客户主键'),
    sa.Column('okki_namespace', sa.String(length=128), nullable=False, comment='外部客户身份命名空间'),
    sa.Column('okki_company_id', sa.String(length=64), nullable=False, comment='小满公司ID，按字符串存储'),
    sa.Column('external_identity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='已审核的外部身份记录'),
    sa.Column('binding_fingerprint', sa.String(length=64), nullable=False, comment='身份与归属语义指纹，不含普通证据刷新'),
    sa.Column('assignment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='已审核的有效主负责人记录'),
    sa.Column('sales_user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('can_view_price', sa.Boolean(), nullable=False, comment='允许查看价格及PI'),
    sa.Column('can_order', sa.Boolean(), nullable=False, comment='允许提交和确认交易条件'),
    sa.Column('auth_version', sa.BigInteger(), nullable=False, comment='访问授权撤销版本'),
    sa.Column('catalog_version', sa.BigInteger(), nullable=False, comment='客户目录授权版本'),
    sa.Column('mapping_version', sa.BigInteger(), nullable=False, comment='客户展示映射版本'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("status IN ('draft','enabled','suspended','review_required')", name='ck_op_access_status'),
    sa.CheckConstraint('can_order = 0 OR can_view_price = 1', name='ck_op_access_order_price'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'site_id', name='uq_op_access_site'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('site_id', 'customer_id', name='uq_op_access_customer'),
    sa.UniqueConstraint('site_id', 'okki_namespace', 'okki_company_id', name='uq_op_access_external')
    )
    op.create_table('ark_order_portal_history_grants',
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('grantee_user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('scope', sa.String(length=24), nullable=False, comment='历史读取授权范围'),
    sa.Column('order_request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户requests关联记录'),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='操作理由，禁止存凭证与完整个人资料'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='服务端撤销时间'),
    sa.Column('created_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("(scope = 'order' AND order_request_id IS NOT NULL) OR (scope = 'request_history' AND order_request_id IS NULL)", name='ck_op_history_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_invitations',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户accounts关联记录'),
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('membership_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户memberships关联记录'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='随机凭证SHA256摘要，不存原令牌'),
    sa.Column('account_version', sa.BigInteger(), nullable=False, comment='签发时账号授权版本'),
    sa.Column('access_version', sa.BigInteger(), nullable=False, comment='签发时客户访问版本'),
    sa.Column('membership_version', sa.BigInteger(), nullable=False, comment='签发时成员版本'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='单次凭证消费时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='服务端撤销时间'),
    sa.Column('created_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'account_id', 'site_id', name='uq_op_invitation_identity'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('ark_order_portal_mapping_revisions',
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='授权或配置版本'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('created_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='正式发布的北京时间'),
    sa.Column('base_version', sa.BigInteger(), nullable=False, comment='编辑开始时的版本'),
    sa.Column('snapshot_json', sa.JSON(), nullable=False, comment='不可变客户映射快照'),
    sa.Column('digest', sa.String(length=64), nullable=False, comment='映射快照SHA256摘要'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("status IN ('draft','published')", name='ck_op_mapping_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'version', name='uq_op_mapping_revision'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_memberships',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户accounts关联记录'),
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='授权或配置版本'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("status IN ('invited','active','disabled')", name='ck_op_member_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'account_id', name='uq_op_member_access_account'),
    sa.UniqueConstraint('id', 'access_id', 'account_id', name='uq_op_member_identity'),
    sa.UniqueConstraint('id', 'account_id', name='uq_op_member_account'),
    sa.UniqueConstraint('id', 'site_id', name='uq_op_member_site'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('site_id', 'account_id', name='uq_op_member_site_account')
    )
    op.create_table('ark_order_portal_outbox',
    sa.Column('event_key', sa.String(length=160), nullable=False, comment='通知业务事件唯一键'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='通知类别'),
    sa.Column('aggregate_public_id', sa.String(length=36), nullable=False, comment='通知所属业务对象'),
    sa.Column('payload_json', sa.JSON(), nullable=False, comment='通知非秘密引用数据'),
    sa.Column('secret_envelope', sa.LargeBinary(), nullable=True, comment='邀请或验证码AES-GCM短期密文'),
    sa.Column('secret_key_version', sa.String(length=32), nullable=True, comment='邮件密钥版本引用'),
    sa.Column('secret_expires_at', sa.DateTime(), nullable=True, comment='秘密事件失效清理时间'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='发送累计尝试次数'),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False, comment='下次发送时间'),
    sa.Column('lease_until', sa.DateTime(), nullable=True, comment='任务租约截止，北京时间'),
    sa.Column('lease_token', sa.String(length=64), nullable=True, comment='任务抢占身份'),
    sa.Column('last_error_code', sa.String(length=64), nullable=True, comment='最近失败的脱敏错误码'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_pi_amendments',
    sa.Column('request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户requests关联记录'),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='唯一关联方舟发票，不允许破坏引用删除'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('active_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户revisions关联记录'),
    sa.Column('accepted_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户revisions关联记录'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("status IN ('current','withdrawn','pending_customer','accepted')", name='ck_op_amendment_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('ark_order_portal_preauth_sessions',
    sa.Column('site_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户sites关联记录'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='随机凭证SHA256摘要，不存原令牌'),
    sa.Column('csrf_nonce', sa.String(length=64), nullable=False, comment='会话CSRF随机因子'),
    sa.Column('csrf_key_version', sa.String(length=32), nullable=False, comment='CSRF签名密钥版本引用'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('consumed_at', sa.DateTime(), nullable=True, comment='单次凭证消费时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'site_id', name='uq_op_preauth_site'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('ark_order_portal_publications',
    sa.Column('request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户requests关联记录'),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='唯一关联方舟发票，不允许破坏引用删除'),
    sa.Column('invoice_document_version', sa.BigInteger(), nullable=False, comment='对应发票portal_document_version'),
    sa.Column('revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户revisions关联记录'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='不可变交易内容摘要'),
    sa.Column('customer_snapshot_json', sa.JSON(), nullable=False, comment='获准对外提供的PI不可变快照'),
    sa.Column('render_template_version', sa.String(length=32), nullable=False, comment='PI渲染模板版本'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('published_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='正式发布的北京时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("status IN ('published','withdrawn')", name='ck_op_publication_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'invoice_document_version', name='uq_op_publication_version'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_quotes',
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户accounts关联记录'),
    sa.Column('membership_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户memberships关联记录'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('authority_versions_json', sa.JSON(), nullable=False, comment='报价与提案依赖的权威版本快照'),
    sa.Column('input_hash', sa.String(length=64), nullable=False, comment='规范化请求载荷摘要'),
    sa.Column('result_hash', sa.String(length=64), nullable=False, comment='服务端报价结果摘要'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='结算币种'),
    sa.Column('product_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='商品合计，不含费用'),
    sa.Column('fees_status', sa.String(length=16), nullable=False, comment='费用待确认或已确认'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='总金额，费用未知时必须为空'),
    sa.Column('lines_json', sa.JSON(), nullable=False, comment='标准SKU和客户展示的报价明细快照'),
    sa.Column('delivery_json', sa.JSON(), nullable=False, comment='已确认收货资料快照'),
    sa.Column('payment_terms_snapshot', sa.JSON(), nullable=False, comment='受控付款条款快照'),
    sa.Column('customer_po', sa.String(length=80), nullable=False, comment='客户采购单号'),
    sa.Column('remark', sa.String(length=1000), nullable=False, comment='对外订单备注'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("fees_status IN ('pending','confirmed')", name='ck_op_quote_fees'),
    sa.CheckConstraint("status IN ('valid','consumed','expired')", name='ck_op_quote_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'access_id', 'account_id', name='uq_op_quote_identity'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('ark_order_portal_rate_buckets',
    sa.Column('scope_key_hash', sa.String(length=64), nullable=False, comment='共享限频作用域摘要'),
    sa.Column('window_start', sa.DateTime(), nullable=False, comment='限频窗口起点，北京时间'),
    sa.Column('count', sa.Integer(), nullable=False, comment='窗口内累计次数'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.PrimaryKeyConstraint('scope_key_hash', 'window_start')
    )
    op.create_table('ark_order_portal_request_lines',
    sa.Column('revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户revisions关联记录'),
    sa.Column('line_key', sa.String(length=36), nullable=False, comment='跨发布快照的稳定明细UUID'),
    sa.Column('catalog_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户catalog_items关联记录'),
    sa.Column('product_kind', sa.String(length=16), nullable=False, comment='标准商品类别，发品或配件'),
    sa.Column('product_id', sa.String(length=64), nullable=False, comment='标准商品ID，按字符串存储'),
    sa.Column('sku_id', sa.String(length=64), nullable=False, comment='标准规格ID，按字符串存储'),
    sa.Column('standard_json', sa.JSON(), nullable=False, comment='不可被客户别名覆盖的标准属性'),
    sa.Column('customer_display_json', sa.JSON(), nullable=False, comment='客户型号颜色货号展示快照'),
    sa.Column('mapping_version', sa.BigInteger(), nullable=False, comment='客户展示映射版本'),
    sa.Column('qty', sa.Integer(), nullable=False, comment='标准销售单位数量'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False, comment='四位精度标准单价'),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='非正折扣金额'),
    sa.Column('line_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='先舍入毛额再加折扣的行额'),
    sa.Column('unit_weight_grams', sa.Numeric(precision=14, scale=6), nullable=True, comment='每销售单位标准克重'),
    sa.Column('price_source', sa.String(length=64), nullable=False, comment='服务器定价来源'),
    sa.Column('price_fingerprint', sa.String(length=64), nullable=False, comment='本行定价依据摘要'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint('qty > 0 AND qty <= 10000 AND unit_price > 0 AND discount_amount <= 0 AND line_amount >= 0', name='ck_op_line_values'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('revision_id', 'catalog_item_id', name='uq_op_line_item'),
    sa.UniqueConstraint('revision_id', 'line_key', name='uq_op_line_key'),
    sa.UniqueConstraint('revision_id', 'product_id', 'sku_id', name='uq_op_line_sku')
    )
    op.create_table('ark_order_portal_requests',
    sa.Column('access_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户customer_access关联记录'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户accounts关联记录'),
    sa.Column('customer_id_snapshot', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='提交时方舟客户ID快照'),
    sa.Column('okki_company_id_snapshot', sa.String(length=64), nullable=False, comment='提交时小满客户ID快照'),
    sa.Column('sales_user_id_snapshot', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('servicing_user_id', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=False, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('public_no', sa.String(length=64), nullable=False, comment='门户可读请求单号'),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False, comment='客户提交意图UUID'),
    sa.Column('client_payload_hash', sa.String(length=64), nullable=False, comment='同键载荷冲突校验摘要'),
    sa.Column('quote_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户quotes关联记录'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('active_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户revisions关联记录'),
    sa.Column('accepted_revision_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户revisions关联记录'),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='唯一关联方舟发票，不允许破坏引用删除'),
    sa.Column('customer_po', sa.String(length=80), nullable=False, comment='客户采购单号'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False, comment='客户请求提交时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("status IN ('submitted','awaiting_customer','ready_for_review','invoice_created','rejected','cancelled')", name='ck_op_request_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_id', 'account_id', 'idempotency_key', name='uq_op_request_key'),
    sa.UniqueConstraint('id', 'access_id', name='uq_op_request_access'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('public_no'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_table('ark_order_portal_revisions',
    sa.Column('request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户requests关联记录'),
    sa.Column('revision_no', sa.Integer(), nullable=False, comment='单请求内递增修订编号'),
    sa.Column('kind', sa.String(length=16), nullable=False, comment='首次请求、提案或PI后续修订'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='结算币种'),
    sa.Column('product_amount', sa.Numeric(precision=14, scale=2), nullable=False, comment='商品合计，不含费用'),
    sa.Column('shipping_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='确认运费，未知为空'),
    sa.Column('packaging_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='确认包装费，数量不乘金额'),
    sa.Column('surcharge_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='确认附加费'),
    sa.Column('surcharge_name', sa.String(length=100), nullable=False, comment='附加费对外名称'),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True, comment='总金额，费用未知时必须为空'),
    sa.Column('fees_status', sa.String(length=16), nullable=False, comment='费用待确认或已确认'),
    sa.Column('delivery_json', sa.JSON(), nullable=False, comment='已确认收货资料快照'),
    sa.Column('payment_terms_snapshot', sa.JSON(), nullable=False, comment='受控付款条款快照'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('authority_versions_json', sa.JSON(), nullable=False, comment='报价与提案依赖的权威版本快照'),
    sa.Column('remark', sa.String(length=1000), nullable=False, comment='对外订单备注'),
    sa.Column('mapping_version', sa.BigInteger(), nullable=False, comment='客户展示映射版本'),
    sa.Column('pricing_fingerprint', sa.String(length=64), nullable=False, comment='定价依据快照摘要'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='不可变交易内容摘要'),
    sa.Column('bound_invoice_document_version', sa.BigInteger(), nullable=True, comment='PI后续提案绑定的文档版本'),
    sa.Column('customer_accepted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='门户accounts关联记录'),
    sa.Column('customer_accepted_at', sa.DateTime(), nullable=True, comment='客户首次接受本修订的时间'),
    sa.Column('created_by', sa.Integer().with_variant(mysql.INTEGER(unsigned=True), 'mysql'), nullable=True, comment='方舟员工ID，不是客户账号ID'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.CheckConstraint("fees_status IN ('pending','confirmed')", name='ck_op_revision_fees'),
    sa.CheckConstraint("kind IN ('submitted','proposal','pi_amendment')", name='ck_op_revision_kind'),
    sa.CheckConstraint('(customer_accepted_by IS NULL AND customer_accepted_at IS NULL) OR (customer_accepted_by IS NOT NULL AND customer_accepted_at IS NOT NULL)', name='ck_op_revision_acceptance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'request_id', name='uq_op_revision_request'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('request_id', 'revision_no', name='uq_op_revision_number')
    )
    op.create_table('ark_order_portal_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='随机凭证SHA256摘要，不存原令牌'),
    sa.Column('account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户accounts关联记录'),
    sa.Column('membership_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='门户memberships关联记录'),
    sa.Column('account_version', sa.BigInteger(), nullable=False, comment='签发时账号授权版本'),
    sa.Column('membership_version', sa.BigInteger(), nullable=False, comment='签发时成员版本'),
    sa.Column('access_version', sa.BigInteger(), nullable=False, comment='签发时客户访问版本'),
    sa.Column('csrf_nonce', sa.String(length=64), nullable=False, comment='会话CSRF随机因子'),
    sa.Column('csrf_key_version', sa.String(length=32), nullable=False, comment='CSRF签名密钥版本引用'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有效期截止，北京时间'),
    sa.Column('idle_expires_at', sa.DateTime(), nullable=False, comment='会话闲置截止时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='服务端撤销时间'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('ark_order_portal_sites',
    sa.Column('code', sa.String(length=32), nullable=False, comment='稳定标识码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='受服务层状态机约束的业务状态'),
    sa.Column('allowed_origin', sa.String(length=255), nullable=False, comment='客户站唯一允许来源'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='结算币种'),
    sa.Column('language', sa.String(length=8), nullable=False, comment='客户站语言'),
    sa.Column('policy_json', sa.JSON(), nullable=False, comment='已批准的经营策略'),
    sa.Column('policy_version', sa.BigInteger(), nullable=False, comment='经营策略版本'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='数据库主键'),
    sa.Column('public_id', sa.String(length=36), nullable=False, comment='对外稳定UUID，不承载授权'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间，北京时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='最后修改时间，北京时间'),
    sa.Column('row_version', sa.BigInteger(), nullable=False, comment='并发更新版本'),
    sa.CheckConstraint("status IN ('enabled','disabled')", name='ck_op_site_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_op_access_sales_status', 'ark_order_portal_customer_access', ['sales_user_id', 'status'], unique=False)
    op.create_index('ix_op_challenge_email_purpose', 'ark_order_portal_auth_challenges', ['email_key_hash', 'purpose', 'created_at'], unique=False)
    op.create_index(op.f('ix_ark_order_portal_rate_buckets_expires_at'), 'ark_order_portal_rate_buckets', ['expires_at'], unique=False)
    op.create_index('ix_op_session_account_revoked', 'ark_order_portal_sessions', ['account_id', 'revoked_at'], unique=False)
    op.create_index('ix_op_catalog_site_status', 'ark_order_portal_catalog_items', ['site_id', 'status'], unique=False)
    op.create_index('ix_op_request_access_submitted', 'ark_order_portal_requests', ['access_id', 'submitted_at', 'id'], unique=False)
    op.create_index('ix_op_request_servicing_status', 'ark_order_portal_requests', ['servicing_user_id', 'status', 'id'], unique=False)
    op.create_index('ix_op_audit_object', 'ark_order_portal_audit_events', ['object_type', 'object_public_id', 'created_at'], unique=False)
    op.create_index('ix_op_outbox_pending', 'ark_order_portal_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_foreign_key('fk_op_customer_access_external_identity_id', 'ark_order_portal_customer_access', 'ark_customer_external_identities', ['external_identity_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_customer_access_sales_user_id', 'ark_order_portal_customer_access', 'ark_users', ['sales_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_customer_access_customer_id', 'ark_order_portal_customer_access', 'ark_customer_accounts', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_customer_access_site_id', 'ark_order_portal_customer_access', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_customer_access_assignment_id', 'ark_order_portal_customer_access', 'ark_customer_assignments', ['assignment_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_memberships_access_id_site_id', 'ark_order_portal_memberships', 'ark_order_portal_customer_access', ['access_id', 'site_id'], ['id', 'site_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_memberships_account_id', 'ark_order_portal_memberships', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_memberships_access_id', 'ark_order_portal_memberships', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_memberships_site_id', 'ark_order_portal_memberships', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_membership_id_site_id', 'ark_order_portal_invitations', 'ark_order_portal_memberships', ['membership_id', 'site_id'], ['id', 'site_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_account_id', 'ark_order_portal_invitations', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_created_by', 'ark_order_portal_invitations', 'ark_users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_site_id', 'ark_order_portal_invitations', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_membership_id', 'ark_order_portal_invitations', 'ark_order_portal_memberships', ['membership_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_access_id', 'ark_order_portal_invitations', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_invitations_membership_id_access_id_account_id', 'ark_order_portal_invitations', 'ark_order_portal_memberships', ['membership_id', 'access_id', 'account_id'], ['id', 'access_id', 'account_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_site_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_invitation_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_invitations', ['invitation_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_preauth_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_preauth_sessions', ['preauth_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_invitation_id_account_id_site_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_invitations', ['invitation_id', 'account_id', 'site_id'], ['id', 'account_id', 'site_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_account_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_auth_challenges_preauth_id_site_id', 'ark_order_portal_auth_challenges', 'ark_order_portal_preauth_sessions', ['preauth_id', 'site_id'], ['id', 'site_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_preauth_sessions_site_id', 'ark_order_portal_preauth_sessions', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_sessions_membership_id', 'ark_order_portal_sessions', 'ark_order_portal_memberships', ['membership_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_sessions_account_id', 'ark_order_portal_sessions', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_sessions_membership_id_account_id', 'ark_order_portal_sessions', 'ark_order_portal_memberships', ['membership_id', 'account_id'], ['id', 'account_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_history_grants_order_request_id', 'ark_order_portal_history_grants', 'ark_order_portal_requests', ['order_request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_history_grants_grantee_user_id', 'ark_order_portal_history_grants', 'ark_users', ['grantee_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_history_grants_order_request_id_access_id', 'ark_order_portal_history_grants', 'ark_order_portal_requests', ['order_request_id', 'access_id'], ['id', 'access_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_history_grants_access_id', 'ark_order_portal_history_grants', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_history_grants_created_by', 'ark_order_portal_history_grants', 'ark_users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_catalog_items_site_id', 'ark_order_portal_catalog_items', 'ark_order_portal_sites', ['site_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_catalog_grants_access_id', 'ark_order_portal_catalog_grants', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_catalog_grants_catalog_item_id', 'ark_order_portal_catalog_grants', 'ark_order_portal_catalog_items', ['catalog_item_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_mapping_revisions_created_by', 'ark_order_portal_mapping_revisions', 'ark_users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_mapping_revisions_access_id', 'ark_order_portal_mapping_revisions', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_quotes_membership_id_access_id_account_id', 'ark_order_portal_quotes', 'ark_order_portal_memberships', ['membership_id', 'access_id', 'account_id'], ['id', 'access_id', 'account_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_quotes_account_id', 'ark_order_portal_quotes', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_quotes_membership_id', 'ark_order_portal_quotes', 'ark_order_portal_memberships', ['membership_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_quotes_access_id', 'ark_order_portal_quotes', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_accepted_revision_id', 'ark_order_portal_requests', 'ark_order_portal_revisions', ['accepted_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_active_revision_id', 'ark_order_portal_requests', 'ark_order_portal_revisions', ['active_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_invoice_id', 'ark_order_portal_requests', 'ark_invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_quote_id_access_id_account_id', 'ark_order_portal_requests', 'ark_order_portal_quotes', ['quote_id', 'access_id', 'account_id'], ['id', 'access_id', 'account_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_active_revision_id_id', 'ark_order_portal_requests', 'ark_order_portal_revisions', ['active_revision_id', 'id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_servicing_user_id', 'ark_order_portal_requests', 'ark_users', ['servicing_user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_accepted_revision_id_id', 'ark_order_portal_requests', 'ark_order_portal_revisions', ['accepted_revision_id', 'id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_sales_user_id_snapshot', 'ark_order_portal_requests', 'ark_users', ['sales_user_id_snapshot'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_id_invoice_id', 'ark_order_portal_requests', 'ark_order_portal_conversions', ['id', 'invoice_id'], ['request_id', 'invoice_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_quote_id', 'ark_order_portal_requests', 'ark_order_portal_quotes', ['quote_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_account_id', 'ark_order_portal_requests', 'ark_order_portal_accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_requests_access_id', 'ark_order_portal_requests', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_revisions_customer_accepted_by', 'ark_order_portal_revisions', 'ark_order_portal_accounts', ['customer_accepted_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_revisions_created_by', 'ark_order_portal_revisions', 'ark_users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_revisions_request_id', 'ark_order_portal_revisions', 'ark_order_portal_requests', ['request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_request_lines_revision_id', 'ark_order_portal_request_lines', 'ark_order_portal_revisions', ['revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_request_lines_catalog_item_id', 'ark_order_portal_request_lines', 'ark_order_portal_catalog_items', ['catalog_item_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_conversions_approved_revision_id_request_id', 'ark_order_portal_conversions', 'ark_order_portal_revisions', ['approved_revision_id', 'request_id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_conversions_invoice_id', 'ark_order_portal_conversions', 'ark_invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_conversions_approved_revision_id', 'ark_order_portal_conversions', 'ark_order_portal_revisions', ['approved_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_conversions_request_id', 'ark_order_portal_conversions', 'ark_order_portal_requests', ['request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_conversions_created_by', 'ark_order_portal_conversions', 'ark_users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_accepted_revision_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_revisions', ['accepted_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_invoice_id', 'ark_order_portal_pi_amendments', 'ark_invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_active_revision_id_request_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_revisions', ['active_revision_id', 'request_id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_active_revision_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_revisions', ['active_revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_accepted_revision_id_request_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_revisions', ['accepted_revision_id', 'request_id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_request_id_invoice_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_conversions', ['request_id', 'invoice_id'], ['request_id', 'invoice_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_pi_amendments_request_id', 'ark_order_portal_pi_amendments', 'ark_order_portal_requests', ['request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_revision_id_request_id', 'ark_order_portal_publications', 'ark_order_portal_revisions', ['revision_id', 'request_id'], ['id', 'request_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_request_id', 'ark_order_portal_publications', 'ark_order_portal_requests', ['request_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_revision_id', 'ark_order_portal_publications', 'ark_order_portal_revisions', ['revision_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_request_id_invoice_id', 'ark_order_portal_publications', 'ark_order_portal_conversions', ['request_id', 'invoice_id'], ['request_id', 'invoice_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_published_by', 'ark_order_portal_publications', 'ark_users', ['published_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_publications_invoice_id', 'ark_order_portal_publications', 'ark_invoices', ['invoice_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_op_audit_events_access_id', 'ark_order_portal_audit_events', 'ark_order_portal_customer_access', ['access_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
    op.add_column("ark_invoices", sa.Column("portal_document_version", sa.BigInteger(), nullable=False, server_default="1"))
    op.execute(sa.text("INSERT INTO ark_order_portal_auth_barriers (code, version) VALUES ('authority', 1)"))


def downgrade():
    raise RuntimeError("Portal data and PI lineage must be preserved; disable the feature instead of downgrading")
