"""add service_fee to synced_payment

Revision ID: 6ad9918124a6
Revises: 002_add_second_supervisor
Create Date: 2026-04-21 15:33:07.894244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ad9918124a6'
down_revision: Union[str, None] = '002_add_second_supervisor'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commission_batch', 'batch_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='批次名称',
               existing_nullable=False)
    op.alter_column('commission_batch', 'period_start',
               existing_type=sa.DATE(),
               comment='周期开始日期',
               existing_nullable=False)
    op.alter_column('commission_batch', 'period_end',
               existing_type=sa.DATE(),
               comment='周期结束日期',
               existing_nullable=False)
    op.alter_column('commission_detail', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='回款单ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='订单ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='客户ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'payment_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='本条回款金额',
               existing_nullable=False)
    op.alter_column('commission_detail', 'salesperson_commission',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='业务员提成金额',
               existing_nullable=False)
    op.alter_column('commission_detail', 'supervisor_commission',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='一级主管提成金额',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('commission_detail', 'calc_rule_note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               comment='计算规则说明',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='客户ID',
               existing_nullable=False)
    op.alter_column('customer_commission_snapshot', 'first_order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='首单订单ID',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'first_order_date',
               existing_type=sa.DATE(),
               comment='首单生效日期',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'salesperson_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='归属业务员ID',
               existing_nullable=False)
    op.alter_column('customer_commission_snapshot', 'salesperson_attribute',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment='业务员属性快照，NULL表示待补充',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'salesperson_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='业务员提成比例',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'supervisor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='一级主管ID',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'supervisor_attribute',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment='一级主管属性快照',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'supervisor_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='一级主管提成比例',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'is_complete',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否完整（有比例即完整）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('customer_commission_snapshot', 'is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_commission_snapshot', 'source',
               existing_type=mysql.ENUM('auto', 'manual', 'import', 'init', collation='utf8mb4_unicode_ci'),
               comment='来源：自动/手工/导入/初始化',
               existing_nullable=True,
               existing_server_default=sa.text("'auto'"))
    op.alter_column('customer_commission_snapshot', 'is_manual_reset',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否人工重置产生',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('customer_commission_snapshot', 'reset_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='重置原因',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'operator',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='操作人',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'operated_at',
               existing_type=mysql.DATETIME(),
               comment='操作时间',
               existing_nullable=True)
    op.alter_column('employee_attribute_history', 'employee_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='关联业务库员工ID',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'attribute_type',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment='开发/分配',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'effective_start',
               existing_type=sa.DATE(),
               comment='生效开始时间',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'effective_end',
               existing_type=sa.DATE(),
               comment='生效结束时间，NULL表示当前有效',
               existing_nullable=True)
    op.alter_column('employee_attribute_history', 'is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('payment_commission_status', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='回款单ID',
               existing_nullable=False)
    op.alter_column('payment_commission_status', 'calculated_at',
               existing_type=mysql.DATETIME(),
               comment='计算时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('supervisor_relation_history', 'salesperson_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='业务员ID',
               existing_nullable=False)
    op.alter_column('supervisor_relation_history', 'supervisor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='一级主管ID',
               existing_nullable=False)
    op.add_column('synced_payment', sa.Column('service_fee', sa.DECIMAL(precision=15, scale=2), server_default='0', nullable=True, comment='交易服务费'))
    op.alter_column('synced_payment', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='业务库回款ID',
               existing_nullable=False)
    op.alter_column('synced_payment', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='关联订单ID',
               existing_nullable=False)
    op.alter_column('synced_payment', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='关联客户ID',
               existing_nullable=False)
    op.alter_column('synced_payment', 'payment_date',
               existing_type=sa.DATE(),
               comment='回款日期',
               existing_nullable=False)
    op.alter_column('synced_payment', 'payment_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='回款金额',
               existing_nullable=False)
    op.alter_column('synced_payment', 'synced_at',
               existing_type=mysql.DATETIME(),
               comment='同步时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synced_payment', 'synced_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='同步时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('synced_payment', 'payment_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='回款金额',
               existing_nullable=False)
    op.alter_column('synced_payment', 'payment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='回款日期',
               existing_nullable=False)
    op.alter_column('synced_payment', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='关联客户ID',
               existing_nullable=False)
    op.alter_column('synced_payment', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='关联订单ID',
               existing_nullable=False)
    op.alter_column('synced_payment', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='业务库回款ID',
               existing_nullable=False)
    op.drop_column('synced_payment', 'service_fee')
    op.alter_column('supervisor_relation_history', 'supervisor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='一级主管ID',
               existing_nullable=False)
    op.alter_column('supervisor_relation_history', 'salesperson_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='业务员ID',
               existing_nullable=False)
    op.alter_column('payment_commission_status', 'calculated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='计算时间',
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('payment_commission_status', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='回款单ID',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('employee_attribute_history', 'effective_end',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效结束时间，NULL表示当前有效',
               existing_nullable=True)
    op.alter_column('employee_attribute_history', 'effective_start',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='生效开始时间',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'attribute_type',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='开发/分配',
               existing_nullable=False)
    op.alter_column('employee_attribute_history', 'employee_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='关联业务库员工ID',
               existing_nullable=False)
    op.alter_column('customer_commission_snapshot', 'operated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='操作时间',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'operator',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='操作人',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'reset_reason',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='重置原因',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'is_manual_reset',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否人工重置产生',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('customer_commission_snapshot', 'source',
               existing_type=mysql.ENUM('auto', 'manual', 'import', 'init', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='来源：自动/手工/导入/初始化',
               existing_nullable=True,
               existing_server_default=sa.text("'auto'"))
    op.alter_column('customer_commission_snapshot', 'is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否当前有效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('customer_commission_snapshot', 'is_complete',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否完整（有比例即完整）',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('customer_commission_snapshot', 'supervisor_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment=None,
               existing_comment='一级主管提成比例',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'supervisor_attribute',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='一级主管属性快照',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'supervisor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='一级主管ID',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'salesperson_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment=None,
               existing_comment='业务员提成比例',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'salesperson_attribute',
               existing_type=mysql.ENUM('develop', 'distribute', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='业务员属性快照，NULL表示待补充',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'salesperson_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='归属业务员ID',
               existing_nullable=False)
    op.alter_column('customer_commission_snapshot', 'first_order_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='首单生效日期',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'first_order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='首单订单ID',
               existing_nullable=True)
    op.alter_column('customer_commission_snapshot', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='客户ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'calc_rule_note',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               comment=None,
               existing_comment='计算规则说明',
               existing_nullable=True)
    op.alter_column('commission_detail', 'supervisor_commission',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='一级主管提成金额',
               existing_nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('commission_detail', 'salesperson_commission',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='业务员提成金额',
               existing_nullable=False)
    op.alter_column('commission_detail', 'payment_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment=None,
               existing_comment='本条回款金额',
               existing_nullable=False)
    op.alter_column('commission_detail', 'customer_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='客户ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'order_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='订单ID',
               existing_nullable=False)
    op.alter_column('commission_detail', 'payment_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='回款单ID',
               existing_nullable=False)
    op.alter_column('commission_batch', 'period_end',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='周期结束日期',
               existing_nullable=False)
    op.alter_column('commission_batch', 'period_start',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='周期开始日期',
               existing_nullable=False)
    op.alter_column('commission_batch', 'batch_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='批次名称',
               existing_nullable=False)
    # ### end Alembic commands ###
