import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const {chromium}=createRequire(import.meta.url)(process.env.PORTAL_PLAYWRIGHT_MODULE||'playwright')
const origin=process.env.PORTAL_PREVIEW_ORIGIN||'http://127.0.0.1:3211',output=process.env.PORTAL_QA_OUTPUT,motion=process.env.PORTAL_UI_MOTION||'reduce',widths=process.env.PORTAL_UI_WIDTHS?process.env.PORTAL_UI_WIDTHS.split(',').map(Number):[1440,390,320]
assert.match(origin,/^http:\/\/127\.0\.0\.1:\d+$/);assert.ok(output);assert.ok(['reduce','no-preference'].includes(motion));assert.ok(widths.every(w=>[1440,390,320].includes(w)));await mkdir(output,{recursive:true})
const race=process.env.PORTAL_ONBOARDING_RACE==='1'
const browser=await chromium.launch({executablePath:process.env.PORTAL_CHROMIUM,headless:true}),results=[]
function gate(){let release;const waiting=new Promise(r=>{release=r});return {waiting,release}}
async function reach(page,target){await target.waitFor({state:'attached'});for(let i=0;i<180;i++){if(await target.evaluate(el=>el===document.activeElement))return;await page.keyboard.press('Tab')}throw new Error('Unreachable '+await target.evaluate(el=>el.outerHTML))}
async function activate(page,target,key='Enter'){await reach(page,target);await page.keyboard.press(key)}
async function type(page,target,value){await reach(page,target);await page.keyboard.press('Control+A');await page.keyboard.press('Backspace');await page.keyboard.type(value);await page.keyboard.press('Tab')}
async function focused(page,target){await target.waitFor();await page.waitForFunction(el=>el===document.activeElement,await target.elementHandle())}
async function geometry(page,dialog){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(await dialog.evaluate(el=>{const r=el.getBoundingClientRect(),bad=[];if(r.left< -1||r.right>innerWidth+1||r.top< -1||r.bottom>innerHeight+1||el.scrollWidth>el.clientWidth+1)bad.push('dialog');for(const field of el.querySelectorAll('input,textarea,.el-dialog__footer button')){const b=field.getBoundingClientRect();if(!b.width||!b.height)continue;if(b.left<r.left-1||b.right>r.right+1)bad.push('horizontal '+field.outerHTML.slice(0,80));if(field.closest('.el-dialog__footer')&&(b.top<r.top-1||b.bottom>r.bottom+1))bad.push('footer')}return bad}),[])}
try{for(const width of widths){
 const context=await browser.newContext({viewport:{width,height:950},reducedMotion:motion});await context.addInitScript(()=>{localStorage.setItem('ark_access_token','synthetic-onboarding-keyboard');sessionStorage.setItem('leshine_welcome_shown_session','1')})
 const page=await context.newPage(),errors=[],writes=[],blocked=[];let readGate,writeGate,candidateMode='ready',catalogMode='ready',writeMode='ready',statusMode='absent',exists=false,scopeDenied=false
 const accessId='11111111-1111-4111-8111-111111111111',productId='22222222-2222-4222-8222-222222222222',company='OnboardingBuyerCompany'.repeat(5).slice(0,100),sales='CurrentAuthorizedSales'.repeat(5).slice(0,100)
 const ready={canonical_customer_id:'9007199254740993',company_display_name:company,customer_code:'C-KEYBOARD',assignment_id:'17',sales_user_id:'5',sales_display_name:sales,okki_identity_id:'27',okki_company_id:'OKKI-KEYBOARD',binding_fingerprint:'a'.repeat(64),ready:true,blocked_reasons:[],existing_access:null}
 const unavailable={...ready,canonical_customer_id:'19',company_display_name:'BlockedIdentityBuyer',ready:false,blocked_reasons:['VERIFIED_IDENTITY_MISSING'],okki_identity_id:null}
 const product={id:productId,model_name:'StandardProductModel'.repeat(7).slice(0,128),color_name:'ApprovedStandardColor'.repeat(7).slice(0,128),length:'20',weight:'100',sale_unit:'piece',status:'published'}
 const access={id:accessId,company_display_name:company,canonical_customer_id:ready.canonical_customer_id,sales_user_id:'5',row_version:1,status:'draft',capabilities:{can_view_price:true,can_order:true},catalog_version:1,mapping_version:1,catalog_item_ids:[productId],accounts:{items:[],total:0,page:1,page_size:20}}
 page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();blocked.push(url.href);return route.abort()})
 await context.route('**/api/**',async route=>{
  const req=route.request(),url=new URL(req.url()),path=url.pathname,send=(data,status=200,message='OK')=>route.fulfill({status,json:{code:status,message,data}})
  if(path==='/api/auth/me')return route.fulfill({json:{id:5,name:'Synthetic employee',roles:[],permissions:['portal_access:read','portal_access:admin']}})
  if(path==='/api/auth/refresh')return route.fulfill({json:{access_token:'synthetic-onboarding-keyboard'}})
  if(!path.startsWith('/api/portal/admin/v1/'))return send({})
  if(req.method()==='GET'){
   const captured=path.endsWith('/onboarding/customers')?candidateMode:path.endsWith('/onboarding/catalog')?catalogMode:statusMode;await readGate?.waiting
   if(path.endsWith('/onboarding/customers'))return captured==='fail'?send({},503,'候选客户暂不可用，请重试。'):send({items:[ready,unavailable],total:2})
   if(path.endsWith('/onboarding/catalog')){if(captured==='denied'){scopeDenied=true;return send({},403,'当前商品或客户授权范围已变化，请重新核对。')}return captured==='fail'?send({},503,'商品选项暂不可用，请重试。'):send({items:url.searchParams.get('keyword')?[]:[product],total:url.searchParams.get('keyword')?0:1})}
   if(path.endsWith('/onboarding/customers/'+ready.canonical_customer_id)){if(captured==='fail')return send({},503,'当前授权暂不可用，请重试。');if(captured==='denied'){scopeDenied=true;return send({},404,'记录不存在或不在当前授权范围内。')}return send({...ready,existing_access:captured==='found'?{id:accessId,status:'draft'}:null})}
   if(path.endsWith('/customers/'+accessId))return scopeDenied?send({},404,'记录不存在或不在当前授权范围内。'):send(access)
   if(path.endsWith('/customers'))return send({items:exists&&!scopeDenied?[access]:[],total:exists&&!scopeDenied?1:0})
   throw new Error('Unexpected read '+path)
  }
  assert.equal(path,'/api/portal/admin/v1/customers');assert.equal(req.method(),'POST');const body=req.postDataJSON(),captured=writeMode;writes.push(body);await writeGate?.waiting
  assert.deepEqual(body,{binding_fingerprint:ready.binding_fingerprint,canonical_customer_id:ready.canonical_customer_id,assignment_id:'17',okki_identity_id:'27',catalog_item_ids:[productId],capabilities:{can_view_price:false,can_order:false}})
  if(captured==='denied'){scopeDenied=true;return send({},403,'当前员工无此操作权限。')}
  if(captured==='stale')return send({},409,'客户归属或唯一外部身份已变化，请重新选择。')
  if(captured==='lost')return route.abort('failed')
  exists=true;return send(access)
 })
 const dialog=page.locator('.portal-onboarding-dialog:visible'),summary=text=>dialog.getByRole('alert').filter({hasText:text}),confirm=()=>dialog.getByRole('checkbox',{name:'我已核对公司身份、负责人、已选商品和客户能力',exact:true})
 async function searchCandidates(mode){candidateMode=mode;readGate=gate();await activate(page,dialog.getByRole('button',{name:'搜索客户',exact:true}));await dialog.getByRole('status').filter({hasText:'正在读取可开通客户…'}).waitFor();readGate.release()}
 async function searchProducts(mode){catalogMode=mode;readGate=gate();await activate(page,dialog.getByRole('button',{name:'刷新商品',exact:true}));await dialog.getByRole('status').filter({hasText:'正在读取可授权商品…'}).waitFor();readGate.release()}
 async function create(mode,retry=false){writeMode=mode;writeGate=gate();await activate(page,dialog.getByRole('button',{name:retry?'重试原内容':'创建授权草稿',exact:true}));await dialog.getByRole('status').filter({hasText:'正在创建客户授权草稿，请等待回执…'}).waitFor();writeGate.release()}
 async function inspect(mode){statusMode=mode;readGate=gate();await activate(page,dialog.getByRole('button',{name:'查询已有授权',exact:true}));await dialog.getByRole('status').filter({hasText:'正在查询已有客户授权…'}).waitFor();readGate.release()}
 try{
  await page.goto(origin+'/portal/customers');await activate(page,page.getByRole('button',{name:'开通客户门户',exact:true}));await dialog.getByText('BlockedIdentityBuyer',{exact:true}).waitFor();assert.equal(await dialog.getByRole('row').filter({hasText:'BlockedIdentityBuyer'}).getByRole('button',{name:'选择此客户',exact:true}).isDisabled(),true)
  // First check error focus before adding loading assertions; this must fail on the original UI.
  candidateMode='fail';await activate(page,dialog.getByRole('button',{name:'搜索客户',exact:true}));await focused(page,summary('候选客户暂不可用，请重试。'));await searchCandidates('fail');await focused(page,summary('候选客户暂不可用，请重试。'));assert.equal(writes.length,0)
  await searchCandidates('ready');await activate(page,dialog.getByRole('row').filter({hasText:company}).getByRole('button',{name:'选择此客户',exact:true}));await dialog.getByRole('checkbox',{name:'授权 '+product.model_name+' '+product.color_name+' '+productId,exact:true}).waitFor({state:'attached'})
  catalogMode='denied';readGate=gate();await activate(page,dialog.getByRole('button',{name:'刷新商品',exact:true}));await dialog.getByRole('status').filter({hasText:'正在读取可授权商品…'}).waitFor();readGate.release();await focused(page,summary('当前商品或客户授权范围已变化，请重新核对。'));await page.waitForFunction(values=>values.every(v=>!document.body.innerText.includes(v)),[company,sales,product.model_name,product.color_name]);assert.equal(writes.length,0);await activate(page,dialog.getByRole('button',{name:'关闭',exact:true}));await dialog.waitFor({state:'hidden'});await focused(page,page.getByRole('button',{name:'开通客户门户',exact:true}));catalogMode='ready';scopeDenied=false;await activate(page,page.getByRole('button',{name:'开通客户门户',exact:true}));await activate(page,dialog.getByRole('row').filter({hasText:company}).getByRole('button',{name:'选择此客户',exact:true}));
  await searchProducts('fail');await focused(page,summary('商品选项暂不可用，请重试。'));await searchProducts('fail');await focused(page,summary('商品选项暂不可用，请重试。'));await searchProducts('ready')
  await activate(page,dialog.getByRole('checkbox',{name:'授权 '+product.model_name+' '+product.color_name+' '+productId,exact:true}),'Space');await activate(page,dialog.getByRole('checkbox',{name:'允许查看价格、订单金额与 PI',exact:true}),'Space');assert.equal(await dialog.getByRole('checkbox',{name:'允许下单及确认交易条件',exact:true}).isChecked(),false);await activate(page,confirm(),'Space')
  await reach(page,dialog.getByRole('textbox',{name:'搜索可授权商品',exact:true}));await page.keyboard.press('ArrowLeft');await page.keyboard.press('Tab');assert.equal(await confirm().isChecked(),true);await type(page,dialog.getByRole('textbox',{name:'搜索可授权商品',exact:true}),'unmatched');await activate(page,dialog.getByRole('button',{name:'搜索商品',exact:true}));await dialog.getByText('初始商品授权 · 已选 1 项',{exact:true}).waitFor();assert.equal(await confirm().isChecked(),true,'Filtering does not change selected authorization')
  await activate(page,dialog.locator('summary'));await geometry(page,dialog);if(!race)assert.deepEqual(await dialog.locator('.selected-items').evaluate(host=>{const box=host.getBoundingClientRect();return [...host.querySelectorAll('.el-tag,.el-tag__content')].filter(el=>{const r=el.getBoundingClientRect();return r.right>box.right+1||r.left<box.left-1||el.scrollWidth>el.clientWidth+1}).map(el=>({class:el.className,client:el.clientWidth,scroll:el.scrollWidth,right:el.getBoundingClientRect().right,containerRight:box.right}))}),[],'Selected full specification remains inside its container without text clipping');await page.screenshot({path:output+'/selection-'+width+'.png',fullPage:true});if(!race){await activate(page,dialog.getByRole('button',{name:'移除授权规格 '+product.model_name+' '+product.color_name+' '+productId,exact:true}));assert.equal(await confirm().isChecked(),false);await dialog.getByText('初始商品授权 · 已选 0 项',{exact:true}).waitFor();await type(page,dialog.getByRole('textbox',{name:'搜索可授权商品',exact:true}),'');await searchProducts('ready');await dialog.getByRole('cell',{name:product.model_name,exact:true}).waitFor();await dialog.getByRole('cell',{name:product.color_name,exact:true}).waitFor();assert.equal(await dialog.locator('.el-table__row .cell').evaluateAll((cells,expected)=>cells.length>=4&&cells.some(el=>el.textContent.includes(expected.model))&&cells.some(el=>el.textContent.includes(expected.color))&&cells.every(el=>getComputedStyle(el).whiteSpace==='normal'&&el.scrollWidth<=el.clientWidth+1),{model:product.model_name,color:product.color_name}),true,'Published standard cells exist and wrap their full content');await activate(page,dialog.getByRole('checkbox',{name:'授权 '+product.model_name+' '+product.color_name+' '+productId,exact:true}),'Space');await activate(page,confirm(),'Space')}
  if(!race){await create('stale');await focused(page,summary('客户归属或唯一外部身份已变化，请重新选择。'));assert.equal(await dialog.getByRole('button',{name:'重试原内容',exact:true}).count(),0);await activate(page,dialog.getByRole('button',{name:'返回选择客户',exact:true}));await activate(page,dialog.getByRole('row').filter({hasText:company}).getByRole('button',{name:'选择此客户',exact:true}));await activate(page,dialog.getByRole('checkbox',{name:'授权 '+product.model_name+' '+product.color_name+' '+productId,exact:true}),'Space');await activate(page,confirm(),'Space')}
  if(!race)await create('lost');else{catalogMode='denied';readGate=gate();await activate(page,dialog.getByRole('button',{name:'刷新商品',exact:true}));await dialog.getByRole('status').filter({hasText:'正在读取可授权商品…'}).waitFor();writeMode='lost';writeGate=gate();await activate(page,dialog.getByRole('button',{name:'创建授权草稿',exact:true}));await dialog.getByRole('status').filter({hasText:'正在创建客户授权草稿，请等待回执…'}).waitFor();readGate.release();await focused(page,summary('当前商品或客户授权范围已变化，请重新核对。'));await page.waitForFunction(values=>values.every(v=>!document.body.innerText.includes(v)),[company,sales,product.model_name,product.color_name]);writeGate.release()};await focused(page,summary('网络连接中断，请按页面提示核对。'));assert.equal(await dialog.getByRole('button',{name:'关闭',exact:true}).isDisabled(),true);if(!race)assert.equal(await dialog.getByRole('textbox',{name:'搜索可授权商品',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await dialog.count(),1)
  const event=page.waitForEvent('dialog'),reload=page.reload({timeout:5000}).then(()=>false,()=>true),unload=await event;assert.equal(unload.type(),'beforeunload');await unload.dismiss();assert.equal(await reload,true);assert.equal(writes.length,race?1:2)
  await inspect('fail');await focused(page,summary('当前授权暂不可用，请重试。'));await inspect('absent');await focused(page,summary('尚未查到已有授权，不能据此判断先前请求未执行。结果未知时请仅重试原内容。'));assert.equal(writes.length,race?1:2)
  await create('denied',true);await focused(page,summary('当前员工无此操作权限。'));await page.waitForFunction(values=>values.every(v=>!document.body.innerText.includes(v)),[company,sales,product.model_name,product.color_name]);assert.equal(await dialog.getByRole('textbox',{name:'搜索可授权商品',exact:true}).count(),0);assert.equal(await dialog.getByRole('button',{name:'关闭',exact:true}).isDisabled(),true);await inspect('denied');await focused(page,summary('记录不存在或不在当前授权范围内。'))
  scopeDenied=false;await create('ready',true);await dialog.waitFor({state:'hidden'});const drawer=page.getByRole('dialog',{name:'客户访问与账号',exact:true});await focused(page,drawer.getByRole('button',{name:'刷新详情',exact:true}));assert.deepEqual(writes.slice(race?0:1),Array(3).fill(writes[race?0:1]));assert.equal(writes.length,race?3:4);assert.equal(await drawer.getByRole('button',{name:'邀请采购账号',exact:true}).isDisabled(),true);await drawer.getByText('暂无采购账号，可在启用客户后发送邀请',{exact:true}).waitFor();assert.deepEqual(errors,[]);assert.ok(blocked.some(v=>new URL(v).hostname==='fonts.googleapis.com'))
  results.push({width,motion,race,keyboard:true,unknownBeforeUnload:true,simulatedWriteAttempts:writes.length,pageErrors:errors.length,lengths:{company:company.length,sales:sales.length,model:product.model_name.length,color:product.color_name.length}})
 }catch(e){await page.screenshot({path:output+'/failure-'+width+'.png',fullPage:true});await writeFile(output+'/failure-'+width+'.json',JSON.stringify(await page.evaluate(()=>({active:document.activeElement?.outerHTML?.slice(0,1000),text:document.body.innerText.slice(-15000)})),null,2));throw e}finally{readGate?.release();writeGate?.release();await context.close()}
}await writeFile(output+'/result.json',JSON.stringify({status:'pass',scope:'Built employee UI, intercepted synthetic onboarding identity/catalog/access APIs; no backend/RBAC/persistence/SMTP proof.',results},null,2));console.log(JSON.stringify({status:'pass',results}))}finally{await browser.close()}