import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const { chromium }=createRequire(import.meta.url)(process.env.PORTAL_PLAYWRIGHT_MODULE || 'playwright')
const origin=process.env.PORTAL_PREVIEW_ORIGIN || 'http://127.0.0.1:3211', output=process.env.PORTAL_QA_OUTPUT, motion=process.env.PORTAL_UI_MOTION || 'reduce', target=process.env.PORTAL_REVIEW_TARGET || 'catalog'
assert.match(origin,/^http:\/\/127\.0\.0\.1:\d+$/);assert.ok(output);assert.ok(['catalog','binding'].includes(target));assert.ok(['reduce','no-preference'].includes(motion));await mkdir(output,{recursive:true})
const widths=process.env.PORTAL_UI_WIDTHS ? process.env.PORTAL_UI_WIDTHS.split(',').map(Number):[1440,390,320]
assert.ok(widths.length && widths.every(x=>[1440,390,320].includes(x)))
function gate(){let release;const waiting=new Promise(resolve=>release=resolve);return {waiting,release}}
async function reach(page,locator){await locator.waitFor({state:'attached'});for(let i=0;i<190;i++){if(await locator.evaluate(el=>el===document.activeElement))return;await page.keyboard.press('Tab')}throw new Error('Unreachable '+await locator.evaluate(el=>el.outerHTML))}
async function activate(page,locator,key='Enter'){await reach(page,locator);await page.keyboard.press(key)}
async function type(page,locator,value){await reach(page,locator);await page.keyboard.press('Control+A');await page.keyboard.press('Backspace');await page.keyboard.type(value);await page.keyboard.press('Tab')}
async function focused(page,locator){await locator.waitFor({state:'visible'});await page.waitForFunction(el=>el===document.activeElement,await locator.elementHandle());assert.equal(await locator.evaluate(el=>el===document.activeElement),true)}
async function geometry(page,dialog){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(await dialog.evaluate(el=>{const r=el.getBoundingClientRect(),bad=[];if(r.left < -1||r.right>innerWidth+1||r.top < -1||r.bottom>innerHeight+1||el.scrollWidth>el.clientWidth+1)bad.push('dialog');for(const b of el.querySelectorAll('.el-dialog__footer button,input,textarea')){const q=b.getBoundingClientRect();if(!q.width||!q.height)continue;if(q.left<r.left-1||q.right>r.right+1)bad.push(b.getAttribute('aria-label')||b.textContent);if(b.closest('.el-dialog__footer')&&(q.top<r.top||q.bottom>r.bottom))bad.push('footer')}return bad}),[])}
const browser=await chromium.launch({executablePath:process.env.PORTAL_CHROMIUM,headless:true}),results=[]
try{for(const width of widths){
 const context=await browser.newContext({viewport:{width,height:950},reducedMotion:motion}),page=await context.newPage(),errors=[],writes=[],blocked=[]
 const id='11111111-1111-4111-8111-111111111111',oldId='22222222-2222-4222-8222-222222222222',freshId='33333333-3333-4333-8333-333333333333',company='PrivateReviewBuyer'.repeat(6).slice(0,100),reason='ConfirmedReviewScope'.repeat(30).slice(0,500),fingerprint='a'.repeat(64)
 const old={id:oldId,model_name:'Withdrawn Model',color_name:'Black',length:'20',weight:'100',sale_unit:'pack',status:'disabled'},fresh={...old,id:freshId,model_name:'PublishedStandardModel'.repeat(8).slice(0,128),color_name:'PublishedStandardColor'.repeat(8).slice(0,128),status:'published'}
 let items=[old],version=1,accessStatus='draft',readMode=target==='catalog'?'fail':'ready',writeMode='ready',pickerMode='ready',scopeDenied=false,writeGate,readGate,pickerGate,refreshGate,permissions=['portal_access:read','portal_access:admin']
 const pending=Array.from({length:1002},(_,i)=>({id:'order-'+(i+1),public_no:'REQ-20261004-'+String(i+1).padStart(6,'0'),status:i%2?'ready_for_review':'submitted',servicing_user_id:'1'}))
 const access=()=>({id,company_display_name:company,row_version:version,status:accessStatus,canonical_customer_id:'9007199254740993',sales_user_id:'1',capabilities:{can_view_price:false,can_order:false},catalog_version:version,mapping_version:1,catalog_item_ids:items.map(x=>x.id),accounts:{items:[],total:0}})
 const binding=()=>({access_id:id,row_version:version,current_sales_user_id:'1',current_company_id:'501',assignments:[{id:'22',sales_user_id:'2',sales_name:'ApprovedNewSales'.repeat(8).slice(0,100)}],identities:[{id:'91',company_id:'5'.repeat(64),namespace:'okki:'.repeat(26).slice(0,128)}],review_fingerprint:fingerprint,requires_assignment_review:false,customer_requires_review:false,pending_requests:pending.slice(0,1000),pending_total:1002,pending_truncated:true,order_total:1003,invoice_order_total:1})
 await context.addInitScript(()=>{localStorage.setItem('ark_access_token','synthetic-review-keyboard');sessionStorage.setItem('leshine_welcome_shown_session','1')})
 page.on('pageerror',e=>errors.push(e.message))
 await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===origin)return route.continue();blocked.push(url.href);return route.abort()})
 await context.route('**/api/**',async route=>{
  const req=route.request(),path=new URL(req.url()).pathname,send=(data,status=200,message='OK')=>route.fulfill({status,json:{code:status,message,data}})
  if(path==='/api/auth/me')return route.fulfill({json:{id:5,name:'Synthetic employee',roles:[],permissions}})
  if(path==='/api/auth/refresh')return route.fulfill({json:{access_token:'synthetic-review-keyboard'}})
  if(!path.startsWith('/api/portal/admin/v1/'))return send({})
  if(req.method()==='GET'){
   if(path.endsWith('/onboarding/catalog')){const mode=pickerMode;await pickerGate?.waiting;if(mode==='denied'){scopeDenied=true;return send({},403,'当前商品范围已变化。')}return send({items:[fresh],total:1})}
   if(path.endsWith('/catalog')||path.endsWith('/binding-review')){assert.ok(path.endsWith('/customers/'+id+'/catalog')||path.endsWith('/customers/'+id+'/binding-review'));const mode=readMode;await readGate?.waiting;if(mode==='fail')return send({},503,'当前复核暂不可用，请重试。');if(mode==='denied'){scopeDenied=true;return send({},403,'当前复核权限已撤销。')}return send(path.endsWith('/catalog')?{...access(),items}:binding())}
   await refreshGate?.waiting
   if(scopeDenied)return send({},403,'当前员工无此操作权限。')
   if(path.endsWith('/customers'))return send({items:[access()],total:1})
   if(path.endsWith('/customers/'+id))return send(access())
   throw new Error('Unexpected GET '+path)
  }
  assert.ok(path.endsWith('/customers/'+id+'/catalog')||path.endsWith('/customers/'+id+'/transfer')||path.endsWith('/customers/'+id+'/rebind'))
  const mode=writeMode,operation={path,method:req.method(),body:req.postDataJSON(),version:req.headers()['if-match']};writes.push(operation);await writeGate?.waiting
  if(mode==='denied'){scopeDenied=true;return send({},403,'当前员工无此操作权限。')}
  if(mode==='stale')return send({},409,'复核记录已变化，请重新读取。')
  if(mode==='lost')return route.abort('failed')
  assert.equal(operation.version,'"'+version+'"');version++
  if(path.endsWith('/catalog')){assert.equal(operation.method,'PATCH');items=[old,fresh].filter(x=>operation.body.catalog_item_ids.includes(x.id));return send({...access(),items})}
  assert.equal(operation.method,'POST')
  return send({...access(),status:'suspended',requires_enable:true,reassigned_request_ids:operation.body.pending_request_ids||[],unassigned_pending_request_ids:pending.filter(x=>!operation.body.pending_request_ids?.includes(x.id)).map(x=>x.id),history_grants:1003-(operation.body.pending_request_ids?.length||0),expired_quotes:2})
 })
 const drawer=page.getByRole('dialog',{name:'客户访问与账号',exact:true}),dialog=page.locator(target==='catalog'?'.portal-catalog-access:visible':'.portal-binding-review:visible'),triggerName=target==='catalog'?'管理商品授权':'归属与身份复核'
 const confirm=()=>dialog.getByRole('checkbox',{name:target==='catalog'?'我已核对新增、移除和保留商品，以及重新登录和报价失效的影响':'我已核对旧绑定、新对象、订单交接及历史读取范围，并确认客户需要重新启用',exact:true}),submit=()=>dialog.getByRole('button',{name:target==='catalog'?'保存商品授权':'确认本次复核',exact:true}),read=()=>dialog.getByRole('button',{name:target==='catalog'?'读取当前授权并放弃草稿':'读取当前复核并放弃草稿',exact:true}),reasonInput=()=>dialog.getByRole('textbox',{name:target==='catalog'?'商品授权操作原因':'复核原因',exact:true})
 async function open(){await activate(page,page.getByRole('button',{name:'管理',exact:true}));await drawer.getByRole('heading',{name:company,exact:true}).waitFor();await activate(page,drawer.getByRole('button',{name:triggerName,exact:true}));await dialog.waitFor()}
 async function inspect(mode){readMode=mode;readGate=gate();await activate(page,read());await dialog.getByRole('status').filter({hasText:target==='catalog'?'正在读取当前商品授权…':'正在读取当前绑定与影响范围…'}).waitFor();assert.equal(await dialog.locator('.review-content').getAttribute('aria-busy'),'true');readGate.release()}
 async function send(mode){writeMode=mode;writeGate=gate();await activate(page,submit());await dialog.getByRole('status').filter({hasText:target==='catalog'?'正在保存商品授权，请等待回执…':'正在提交客户复核，请等待回执…'}).waitFor();assert.equal(await dialog.locator('.review-content').getAttribute('aria-busy'),'true');writeGate.release()}
 async function choose(label){const input=dialog.getByRole('combobox',{name:label,exact:true});await activate(page,input);await page.getByRole('option').first().waitFor();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');const expected=label==='新主负责人'?'归属 22':'5'.repeat(64);await page.waitForFunction(({el,expected})=>el.closest('.el-select').textContent.includes(expected),{el:await input.elementHandle(),expected})}
 async function fillTransfer(){await choose('新主负责人');await activate(page,dialog.getByRole('checkbox',{name:'交接 '+pending[0].public_no,exact:true}),'Space');await activate(page,dialog.locator('.el-pagination .btn-next'));await activate(page,dialog.getByRole('checkbox',{name:'交接 '+pending[20].public_no,exact:true}),'Space');await reach(page,dialog.getByRole('radio',{name:'不新增历史读取',exact:true}));await page.keyboard.press('ArrowRight');assert.equal(await dialog.getByRole('radio',{name:'向新负责人限时授权',exact:true}).isChecked(),true);await type(page,dialog.getByRole('spinbutton',{name:'历史读取有效天数',exact:true}),'365');await type(page,reasonInput(),reason)}
 async function hiddenPrivate(){await page.waitForFunction(values=>values.every(x=>!document.body.innerText.includes(x)),[company,reason,fresh.model_name,fresh.color_name]);assert.equal(await reasonInput().count(),0)}
 try{
  await page.goto(origin+'/portal/customers');await open()
  if(target==='catalog'){
   const failed=dialog.getByRole('alert').filter({hasText:'当前复核暂不可用，请重试。'});await focused(page,failed);await activate(page,read());await focused(page,failed);assert.equal(writes.length,0);await inspect('ready');await focused(page,dialog.getByRole('alert').filter({hasText:'已读取当前授权并放弃本地草稿'}))
   await activate(page,dialog.getByRole('checkbox',{name:'授权 '+fresh.model_name+' '+fresh.color_name+' '+fresh.id,exact:true}),'Space');await activate(page,dialog.locator('summary'));await activate(page,dialog.getByRole('button',{name:'移除授权规格 '+old.model_name+' '+old.color_name+' '+old.id,exact:true}));await type(page,reasonInput(),reason)
  }else{
   await activate(page,confirm(),'Space');await activate(page,submit());const invalid=dialog.getByRole('alert').filter({hasText:'请填写 1–500 字的复核原因。'});await focused(page,invalid);await activate(page,submit());await focused(page,invalid);assert.equal(writes.length,0);await fillTransfer();assert.equal(await dialog.locator('.el-pagination__total').textContent(),'共 1000 条')
   if(width<600){const scroll=dialog.locator('.el-table .el-scrollbar__wrap').first();await reach(page,scroll);const before=await scroll.evaluate(el=>el.scrollLeft);await page.keyboard.press('ArrowRight');await page.waitForFunction(el=>el.scrollLeft>0,await scroll.elementHandle());assert.ok(await scroll.evaluate(el=>el.scrollLeft)>before)}
  }
  await activate(page,confirm(),'Space');await reach(page,reasonInput());await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowRight');await page.keyboard.press('Tab');assert.equal(await confirm().isChecked(),true);await type(page,reasonInput(),reason.slice(0,-1));assert.equal(await confirm().isChecked(),false);assert.equal(await submit().isDisabled(),true);await type(page,reasonInput(),reason);await activate(page,confirm(),'Space');await geometry(page,dialog);await page.screenshot({path:output+'/prepared-'+target+'-'+width+'.png',fullPage:true})
  await send('stale');const stale=dialog.getByRole('alert').filter({hasText:'复核记录已变化，请重新读取。'});await focused(page,stale);await send('stale');await focused(page,stale);assert.equal(await reasonInput().inputValue(),reason)
  await send('lost');await focused(page,dialog.getByRole('alert').filter({hasText:'网络连接中断，请按页面提示核对。'}));assert.equal(await reasonInput().isDisabled(),true);assert.equal(await dialog.getByRole('button',{name:'关闭',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await dialog.count(),1)
  const before=writes.length,beforeUnload=page.waitForEvent('dialog'),reload=page.reload({timeout:5000}).then(()=>false,()=>true),unload=await beforeUnload;assert.equal(unload.type(),'beforeunload');await unload.dismiss();assert.equal(await reload,true);assert.equal(writes.length,before)
  await inspect('fail');const failed=dialog.getByRole('alert').filter({hasText:'当前复核暂不可用，请重试。'});await focused(page,failed);await inspect('fail');await focused(page,failed);assert.equal(await reasonInput().isDisabled(),true)
  await inspect('denied');await focused(page,dialog.getByRole('alert').filter({hasText:'当前复核权限已撤销。'}));await hiddenPrivate();assert.equal(await dialog.getByRole('button',{name:'关闭',exact:true}).isDisabled(),true);assert.equal(writes.length,3);await geometry(page,dialog)
  scopeDenied=false;await inspect('ready');const notice=dialog.getByRole('alert').filter({hasText:target==='catalog'?'已读取当前授权并放弃本地草稿':'已读取当前绑定与影响范围并放弃草稿'});await focused(page,notice);assert.equal(await confirm().isChecked(),false);assert.equal(await reasonInput().inputValue(),'');assert.equal(writes.length,3)
  await activate(page,dialog.getByRole('button',{name:'关闭',exact:true}));await dialog.waitFor({state:'hidden'});await focused(page,page.getByRole('button',{name:'管理',exact:true}));await open()
  if(target==='catalog')await type(page,reasonInput(),reason);else await fillTransfer();await activate(page,confirm(),'Space');await send('ready');await dialog.waitFor({state:'hidden'});await focused(page,drawer.getByRole('button',{name:triggerName,exact:true}));assert.equal(writes.length,4)
  if(target==='catalog'){
   await activate(page,drawer.getByRole('button',{name:triggerName,exact:true}));await reasonInput().waitFor();accessStatus='review_required';await inspect('ready');await focused(page,dialog.getByRole('alert').filter({hasText:'已读取当前授权并放弃本地草稿'}));await activate(page,dialog.getByRole('button',{name:'关闭',exact:true}));await dialog.waitFor({state:'hidden'});await focused(page,drawer.getByRole('button',{name:'刷新详情',exact:true}));assert.equal(await drawer.getByRole('button',{name:triggerName,exact:true}).isDisabled(),true)
   accessStatus='draft';await activate(page,drawer.getByRole('button',{name:'刷新详情',exact:true}));await page.waitForFunction(el=>!el.disabled,await drawer.getByRole('button',{name:triggerName,exact:true}).elementHandle())
  }
  const expected=target==='catalog'?{catalog_item_ids:[fresh.id],reason}:{review_fingerprint:fingerprint,reason,assignment_id:'22',pending_request_ids:['order-1','order-21'],history_policy:'explicit_grant',history_days:365};assert.deepEqual(writes.slice(0,3).map(x=>x.body),[expected,expected,expected]);assert.ok(writes.slice(0,3).every(x=>x.version==='"1"'));assert.equal(version,2)
  await activate(page,drawer.getByRole('button',{name:triggerName,exact:true}));await reasonInput().waitFor()
  if(target==='binding'){await reach(page,dialog.getByRole('radio',{name:'复核负责人转交',exact:true}));await page.keyboard.press('ArrowRight');assert.equal(await dialog.getByRole('radio',{name:'重绑外部公司身份',exact:true}).isChecked(),true);await choose('已验证外部公司身份')}
  await type(page,reasonInput(),reason);await activate(page,confirm(),'Space');refreshGate=gate();await send('ready');await dialog.waitFor({state:'hidden'});await page.keyboard.press('Escape');await drawer.waitFor({state:'hidden'});const search=page.getByRole('textbox',{name:'搜索客户',exact:true});await reach(page,search);await page.keyboard.type('NewReviewSearch');refreshGate.release();await page.getByRole('button',{name:'管理',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.portal-customers .el-loading-mask'));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await search.evaluate(el=>el===document.activeElement),true);assert.equal(await search.inputValue(),'NewReviewSearch')
  if(target==='binding'){assert.ok(writes[4].path.endsWith('/rebind'));assert.deepEqual(writes[4].body,{review_fingerprint:fingerprint,reason,identity_id:'91'})}
  if(target==='catalog'){
   await open();await reasonInput().waitFor();await dialog.getByText(fresh.model_name,{exact:true}).waitFor()
   pickerMode='denied';pickerGate=gate();await activate(page,dialog.getByRole('button',{name:'刷新商品',exact:true}));await dialog.getByRole('status').filter({hasText:'正在读取可授权商品…'}).waitFor()
   await type(page,reasonInput(),reason);await activate(page,confirm(),'Space');writeMode='lost';writeGate=gate();await activate(page,submit());await dialog.getByRole('status').filter({hasText:'正在保存商品授权，请等待回执…'}).waitFor()
   pickerGate.release();await focused(page,dialog.getByRole('alert').filter({hasText:'当前商品或客户授权范围已变化，请重新核对。'}));await hiddenPrivate();assert.equal(await dialog.getByRole('status').filter({hasText:'正在保存商品授权，请等待回执…'}).isVisible(),true);assert.equal(await dialog.getByRole('button',{name:'关闭',exact:true}).isDisabled(),true)
   writeGate.release();await focused(page,dialog.getByRole('alert').filter({hasText:'网络连接中断，请按页面提示核对。'}));await dialog.getByRole('alert').filter({hasText:'保存结果未知，当前选择已冻结。'}).waitFor();assert.equal(writes.length,6);assert.deepEqual(writes[5].body,{catalog_item_ids:items.map(x=>x.id),reason});assert.equal(writes[5].version,'"'+version+'"')
   scopeDenied=false;pickerMode='ready';await inspect('ready');await focused(page,dialog.getByRole('alert').filter({hasText:'已读取当前授权并放弃本地草稿'}));assert.equal(writes.length,6,'Auxiliary denial must retain read-only unknown recovery without another write');await activate(page,dialog.getByRole('button',{name:'关闭',exact:true}));await dialog.waitFor({state:'hidden'});await focused(page,page.getByRole('button',{name:'管理',exact:true}))
  }

  await open();await type(page,reasonInput(),reason);if(target==='binding')await choose('新主负责人');await activate(page,confirm(),'Space');await send('denied');await focused(page,dialog.getByRole('alert').filter({hasText:'当前员工无此操作权限。'}));await hiddenPrivate();assert.equal(await submit().isDisabled(),true);await activate(page,dialog.getByRole('button',{name:'关闭',exact:true}));await dialog.waitFor({state:'hidden'});await focused(page,page.getByRole('button',{name:'刷新',exact:true}))
  scopeDenied=false;permissions=['portal_access:read'];await page.reload();await activate(page,page.getByRole('button',{name:'管理',exact:true}));await drawer.getByRole('heading',{name:company,exact:true}).waitFor();assert.equal(await drawer.getByRole('button',{name:triggerName,exact:true}).isVisible(),false)
  assert.equal(writes.length,target==='catalog'?7:6);assert.deepEqual(errors,[]);assert.ok(blocked.some(url=>new URL(url).hostname==='fonts.googleapis.com'));results.push({width,target,motion,keyboard:true,unknownReadOnly:true,auxiliaryDenialDuringSave:target==='catalog',lateRefreshProtected:true,simulatedWrites:writes.length,pageErrors:errors.length,lengths:{company:company.length,reason:reason.length,model:fresh.model_name.length,color:fresh.color_name.length},pendingRows:target==='binding'?1000:0})
 }catch(error){await page.screenshot({path:output+'/failure-'+target+'-'+width+'.png',fullPage:true});await writeFile(output+'/failure-'+target+'-'+width+'.json',JSON.stringify(await page.evaluate(()=>({active:document.activeElement?.outerHTML?.slice(0,900),text:document.body.innerText.slice(-13000)})),null,2));throw error}
 finally{writeGate?.release();readGate?.release();pickerGate?.release();refreshGate?.release();await context.close()}
 }
 const result={status:'pass',scope:'Built employee UI, synthetic intercepted catalog/binding/identity APIs. No real RBAC, persistence, transaction or SMTP proof.',results};await writeFile(output+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result))
}finally{await browser.close()}