import assert from 'node:assert/strict'
import test from 'node:test'
import {shipmentSubmissionKey,copyShipment,readShipmentSubmission,saveShipmentSubmission,clearShipmentSubmission,isShipmentReceipt,isShipmentObservation,uncertainShipment} from '../src/views/invoice/composables/shipmentSubmission.js'
const command=()=>({invoice_id:1,body:{items:[{invoice_item_id:7,quantity:4}],freight_amount:'20.00',quote_hash:'a'.repeat(64),request_key:'original_shipment_123',payment:{amount:'32.00',bank_charge:'0',collection_date:'2026-10-06',payment_type:'T/T',attachment_ids:['proof'],remark:'ORIGINAL'}}})
function memory(){const data=new Map();return{data,getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)}}
test('exact original invoice/body stays immutable across form edits',()=>{const store=memory(),original=command();saveShipmentSubmission(store,1,original);original.invoice_id=2;original.body.items[0].quantity=9;original.body.payment.attachment_ids.push('other');assert.deepEqual(readShipmentSubmission(store,1),command());const restored=readShipmentSubmission(store,1);restored.body.payment.remark='EDITED';assert.equal(readShipmentSubmission(store,1).body.payment.remark,'ORIGINAL')})
test('actor slots and one pending invoice cannot be overwritten',()=>{const store=memory(),original=command();saveShipmentSubmission(store,1,original);assert.equal(readShipmentSubmission(store,2),null);for(const changed of [{...original,invoice_id:2},{...original,body:{...original.body,freight_amount:'30'}}])assert.throws(()=>saveShipmentSubmission(store,1,changed));clearShipmentSubmission(store,1,'wrong');assert.deepEqual(readShipmentSubmission(store,1),original);clearShipmentSubmission(store,1,original.body.request_key);assert.equal(readShipmentSubmission(store,1),null)})
test('storage quota, silently dropped writes and corruption stop financial POST preparation',()=>{const store=memory();store.setItem=()=>{};assert.throws(()=>saveShipmentSubmission(store,1,command()));store.setItem=()=>{throw Error('quota')};assert.throws(()=>saveShipmentSubmission(store,1,command()));store.data.set(shipmentSubmissionKey(1),'not JSON');assert.throws(()=>readShipmentSubmission(store,1));store.data.set(shipmentSubmissionKey(1),JSON.stringify({actor:2,...command()}));assert.throws(()=>readShipmentSubmission(store,1));for(const actor of [0,NaN,1.5])assert.throws(()=>readShipmentSubmission(store,actor))})
test('invalid item IDs/duplicates, quote and financial representations never qualify for storage',()=>{for(const change of [{items:[{invoice_item_id:true,quantity:4}]},{items:[{invoice_item_id:7,quantity:4},{invoice_item_id:7,quantity:2}]},{freight_amount:'NaN'},{freight_amount:'1.001'},{quote_hash:'bad'}]){const value=command();Object.assign(value.body,change);assert.throws(()=>saveShipmentSubmission(memory(),1,value))}const noPayment=command();delete noPayment.body.payment;saveShipmentSubmission(memory(),1,noPayment)})
test('only matching original invoice/key/hash and complete authorized receipt can resolve',()=>{const original=command(),result={id:8,invoice_id:1,request_key:original.body.request_key,quote_hash:original.body.quote_hash,version:1,settlement_no:'S-1',state:'cancelled',quote:{}};assert.ok(isShipmentReceipt(result,original));for(const change of [{id:true},{invoice_id:2},{quote_hash:'b'.repeat(64)},{request_key:'another'},{version:0},{settlement_no:''},{quote:null},{quote:[]}])assert.ok(!isShipmentReceipt({...result,...change},original));assert.deepEqual(copyShipment(original),original)})
test('unknown outcomes remain frozen even after later definitive rejections',()=>{for(const status of [401,403,404,409,422,503])assert.equal(uncertainShipment({response:{status}},true),true);for(const error of [Error('network'),{response:{status:408}},{response:{status:503}}])assert.equal(uncertainShipment(error),true);assert.equal(uncertainShipment({response:{status:409}}),false)})

test('absence validates exact original item identities/quantities and is never a receipt',()=>{const original=command(),result={state:'not_found',request_key:original.body.request_key,invoice:{id:1,items:[{id:7,quantity:4}]}};assert.ok(isShipmentObservation(result,original));assert.ok(!isShipmentReceipt(result,original));for(const rows of [[],[{id:7,quantity:5}],[{id:8,quantity:4}],[{id:7,quantity:true}],[{id:7,quantity:4},{id:7,quantity:4}]])assert.ok(!isShipmentObservation({...result,invoice:{id:1,items:rows}},original));assert.ok(!isShipmentObservation({...result,state:'found'},original))})
